/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * Details of notifications which should be added to the notification scheme.
 **/

public class AddNotificationsDetails extends HashMap<String, Object> {

	/**
	 * The list of notifications which should be added to the notification scheme.
	 **/

	private List<NotificationSchemeEventDetails> notificationSchemeEvents = new ArrayList<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The list of notifications which should be added to the notification scheme.
	 * @return notificationSchemeEvents
	 **/
	public List<NotificationSchemeEventDetails> getNotificationSchemeEvents() {
		return notificationSchemeEvents;
	}

	/**
	 * Set notificationSchemeEvents
	 **/
	public void setNotificationSchemeEvents(List<NotificationSchemeEventDetails> notificationSchemeEvents) {
		this.notificationSchemeEvents = notificationSchemeEvents;
	}

	public AddNotificationsDetails notificationSchemeEvents(List<NotificationSchemeEventDetails> notificationSchemeEvents) {
		this.notificationSchemeEvents = notificationSchemeEvents;
		return this;
	}

	public AddNotificationsDetails addNotificationSchemeEventsItem(NotificationSchemeEventDetails notificationSchemeEventsItem) {
		if (this.notificationSchemeEvents == null) {
			this.notificationSchemeEvents = new ArrayList<>();
		}
		this.notificationSchemeEvents.add(notificationSchemeEventsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {
		String sb = "class AddNotificationsDetails {\n" +
			"    " + toIndentedString(super.toString()) + "\n" +
			"    notificationSchemeEvents: " + toIndentedString(notificationSchemeEvents) + "\n" +
			"}";
		return sb;
	}
}
