/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.List;

/**
 * Metadata for an archive (for example a zip) and its contents.
 **/

public class AttachmentArchiveMetadataReadable {

	/**
	 * The list of the items included in the archive.
	 **/

	private List<AttachmentArchiveItemReadable> entries = null;

	/**
	 * The ID of the attachment.
	 **/

	private Long id;

	/**
	 * The MIME type of the attachment.
	 **/

	private String mediaType;

	/**
	 * The name of the archive file.
	 **/

	private String name;

	/**
	 * The number of items included in the archive.
	 **/

	private Long totalEntryCount;

	public AttachmentArchiveMetadataReadable() {
	}


	public AttachmentArchiveMetadataReadable(
		List<AttachmentArchiveItemReadable> entries,
		Long id,
		String mediaType,
		String name,
		Long totalEntryCount
	) {
		this.entries = entries;
		this.id = id;
		this.mediaType = mediaType;
		this.name = name;
		this.totalEntryCount = totalEntryCount;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The list of the items included in the archive.
	 * @return entries
	 **/
	public List<AttachmentArchiveItemReadable> getEntries() {
		return entries;
	}

	/**
	 * The ID of the attachment.
	 * @return id
	 **/
	public Long getId() {
		return id;
	}

	/**
	 * The MIME type of the attachment.
	 * @return mediaType
	 **/
	public String getMediaType() {
		return mediaType;
	}

	/**
	 * The name of the archive file.
	 * @return name
	 **/
	public String getName() {
		return name;
	}

	/**
	 * The number of items included in the archive.
	 * @return totalEntryCount
	 **/
	public Long getTotalEntryCount() {
		return totalEntryCount;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class AttachmentArchiveMetadataReadable {\n" +
			"    entries: " + toIndentedString(entries) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"    mediaType: " + toIndentedString(mediaType) + "\n" +
			"    name: " + toIndentedString(name) + "\n" +
			"    totalEntryCount: " + toIndentedString(totalEntryCount) + "\n" +
			"}";
		return sb;
	}
}
