/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.List;

/**
 * Container for a list of audit records.
 **/

public class AuditRecords {

	/**
	 * The requested or default limit on the number of audit items to be returned.
	 **/

	private Integer limit;

	/**
	 * The number of audit items skipped before the first item in this list.
	 **/

	private Integer offset;

	/**
	 * The list of audit items.
	 **/

	private List<AuditRecordBean> records = null;

	/**
	 * The total number of audit items returned.
	 **/

	private Long total;

	public AuditRecords() {
	}


	public AuditRecords(
		Integer limit,
		Integer offset,
		List<AuditRecordBean> records,
		Long total
	) {
		this.limit = limit;
		this.offset = offset;
		this.records = records;
		this.total = total;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The requested or default limit on the number of audit items to be returned.
	 * @return limit
	 **/
	public Integer getLimit() {
		return limit;
	}

	/**
	 * The number of audit items skipped before the first item in this list.
	 * @return offset
	 **/
	public Integer getOffset() {
		return offset;
	}

	/**
	 * The list of audit items.
	 * @return records
	 **/
	public List<AuditRecordBean> getRecords() {
		return records;
	}

	/**
	 * The total number of audit items returned.
	 * @return total
	 **/
	public Long getTotal() {
		return total;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class AuditRecords {\n" +
			"    limit: " + toIndentedString(limit) + "\n" +
			"    offset: " + toIndentedString(offset) + "\n" +
			"    records: " + toIndentedString(records) + "\n" +
			"    total: " + toIndentedString(total) + "\n" +
			"}";
		return sb;
	}
}
