/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Details of project permissions and associated issues and projects to look up.
 **/

public class BulkProjectPermissions {

	/**
	 * List of issue IDs.
	 **/

	private Set<Long> issues = null;

	/**
	 * List of project permissions.
	 **/

	private Set<String> permissions = new LinkedHashSet<>();

	/**
	 * List of project IDs.
	 **/

	private Set<Long> projects = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * List of issue IDs.
	 * @return issues
	 **/
	public Set<Long> getIssues() {
		return issues;
	}

	/**
	 * Set issues
	 **/
	public void setIssues(Set<Long> issues) {
		this.issues = issues;
	}

	public BulkProjectPermissions issues(Set<Long> issues) {
		this.issues = issues;
		return this;
	}

	public BulkProjectPermissions addIssuesItem(Long issuesItem) {
		if (this.issues == null) {
			this.issues = new LinkedHashSet<>();
		}
		this.issues.add(issuesItem);
		return this;
	}

	/**
	 * List of project permissions.
	 * @return permissions
	 **/
	public Set<String> getPermissions() {
		return permissions;
	}

	/**
	 * Set permissions
	 **/
	public void setPermissions(Set<String> permissions) {
		this.permissions = permissions;
	}

	public BulkProjectPermissions permissions(Set<String> permissions) {
		this.permissions = permissions;
		return this;
	}

	public BulkProjectPermissions addPermissionsItem(String permissionsItem) {
		if (this.permissions == null) {
			this.permissions = new LinkedHashSet<>();
		}
		this.permissions.add(permissionsItem);
		return this;
	}

	/**
	 * List of project IDs.
	 * @return projects
	 **/
	public Set<Long> getProjects() {
		return projects;
	}

	/**
	 * Set projects
	 **/
	public void setProjects(Set<Long> projects) {
		this.projects = projects;
	}

	public BulkProjectPermissions projects(Set<Long> projects) {
		this.projects = projects;
		return this;
	}

	public BulkProjectPermissions addProjectsItem(Long projectsItem) {
		if (this.projects == null) {
			this.projects = new LinkedHashSet<>();
		}
		this.projects.add(projectsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class BulkProjectPermissions {\n" +
			"    issues: " + toIndentedString(issues) + "\n" +
			"    permissions: " + toIndentedString(permissions) + "\n" +
			"    projects: " + toIndentedString(projects) + "\n" +
			"}";
		return sb;
	}
}
