/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

public class CustomContextVariable {

	/**
	 * Type of custom context variable.
	 **/

	private String type;

	/**
	 * The account ID of the user.
	 **/

	private String accountId;

	/**
	 * The issue ID.
	 **/

	private Long id;

	/**
	 * The issue key.
	 **/

	private String key;

	/**
	 * A JSON object containing custom content.
	 **/

	private Object value;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Type of custom context variable.
	 * @return type
	 **/
	public String getType() {
		return type;
	}

	/**
	 * Set type
	 **/
	public void setType(String type) {
		this.type = type;
	}

	public CustomContextVariable type(String type) {
		this.type = type;
		return this;
	}

	/**
	 * The account ID of the user.
	 * @return accountId
	 **/
	public String getAccountId() {
		return accountId;
	}

	/**
	 * Set accountId
	 **/
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public CustomContextVariable accountId(String accountId) {
		this.accountId = accountId;
		return this;
	}

	/**
	 * The issue ID.
	 * @return id
	 **/
	public Long getId() {
		return id;
	}

	/**
	 * Set id
	 **/
	public void setId(Long id) {
		this.id = id;
	}

	public CustomContextVariable id(Long id) {
		this.id = id;
		return this;
	}

	/**
	 * The issue key.
	 * @return key
	 **/
	public String getKey() {
		return key;
	}

	/**
	 * Set key
	 **/
	public void setKey(String key) {
		this.key = key;
	}

	public CustomContextVariable key(String key) {
		this.key = key;
		return this;
	}

	/**
	 * A JSON object containing custom content.
	 * @return value
	 **/
	public Object getValue() {
		return value;
	}

	/**
	 * Set value
	 **/
	public void setValue(Object value) {
		this.value = value;
	}

	public CustomContextVariable value(Object value) {
		this.value = value;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class CustomContextVariable {\n" +
			"    type: " + toIndentedString(type) + "\n" +
			"    accountId: " + toIndentedString(accountId) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"    key: " + toIndentedString(key) + "\n" +
			"    value: " + toIndentedString(value) + "\n" +
			"}";
		return sb;
	}
}
