/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Details of a dashboard.
 **/

public class DashboardDetails {

	/**
	 * The description of the dashboard.
	 **/

	private String description;

	/**
	 * The edit permissions for the dashboard.
	 **/

	private List<SharePermission> editPermissions = new ArrayList<>();

	/**
	 * The name of the dashboard.
	 **/

	private String name;

	/**
	 * The share permissions for the dashboard.
	 **/

	private List<SharePermission> sharePermissions = new ArrayList<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The description of the dashboard.
	 * @return description
	 **/
	public String getDescription() {
		return description;
	}

	/**
	 * Set description
	 **/
	public void setDescription(String description) {
		this.description = description;
	}

	public DashboardDetails description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * The edit permissions for the dashboard.
	 * @return editPermissions
	 **/
	public List<SharePermission> getEditPermissions() {
		return editPermissions;
	}

	/**
	 * Set editPermissions
	 **/
	public void setEditPermissions(List<SharePermission> editPermissions) {
		this.editPermissions = editPermissions;
	}

	public DashboardDetails editPermissions(List<SharePermission> editPermissions) {
		this.editPermissions = editPermissions;
		return this;
	}

	public DashboardDetails addEditPermissionsItem(SharePermission editPermissionsItem) {
		if (this.editPermissions == null) {
			this.editPermissions = new ArrayList<>();
		}
		this.editPermissions.add(editPermissionsItem);
		return this;
	}

	/**
	 * The name of the dashboard.
	 * @return name
	 **/
	public String getName() {
		return name;
	}

	/**
	 * Set name
	 **/
	public void setName(String name) {
		this.name = name;
	}

	public DashboardDetails name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * The share permissions for the dashboard.
	 * @return sharePermissions
	 **/
	public List<SharePermission> getSharePermissions() {
		return sharePermissions;
	}

	/**
	 * Set sharePermissions
	 **/
	public void setSharePermissions(List<SharePermission> sharePermissions) {
		this.sharePermissions = sharePermissions;
	}

	public DashboardDetails sharePermissions(List<SharePermission> sharePermissions) {
		this.sharePermissions = sharePermissions;
		return this;
	}

	public DashboardDetails addSharePermissionsItem(SharePermission sharePermissionsItem) {
		if (this.sharePermissions == null) {
			this.sharePermissions = new ArrayList<>();
		}
		this.sharePermissions.add(sharePermissionsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class DashboardDetails {\n" +
			"    description: " + toIndentedString(description) + "\n" +
			"    editPermissions: " + toIndentedString(editPermissions) + "\n" +
			"    name: " + toIndentedString(name) + "\n" +
			"    sharePermissions: " + toIndentedString(sharePermissions) + "\n" +
			"}";
		return sb;
	}
}
