/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

/**
 * The data classification.
 **/

public class DataClassificationTagBean {

	/**
	 * The color of the data classification object.
	 **/

	private String color;

	/**
	 * The description of the data classification object.
	 **/

	private String description;

	/**
	 * The guideline of the data classification object.
	 **/

	private String guideline;

	/**
	 * The ID of the data classification object.
	 **/

	private String id;

	/**
	 * The name of the data classification object.
	 **/

	private String name;

	/**
	 * The rank of the data classification object.
	 **/

	private Integer rank;

	/**
	 * The status of the data classification object.
	 **/

	private String status;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The color of the data classification object.
	 * @return color
	 **/
	public String getColor() {
		return color;
	}

	/**
	 * Set color
	 **/
	public void setColor(String color) {
		this.color = color;
	}

	public DataClassificationTagBean color(String color) {
		this.color = color;
		return this;
	}

	/**
	 * The description of the data classification object.
	 * @return description
	 **/
	public String getDescription() {
		return description;
	}

	/**
	 * Set description
	 **/
	public void setDescription(String description) {
		this.description = description;
	}

	public DataClassificationTagBean description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * The guideline of the data classification object.
	 * @return guideline
	 **/
	public String getGuideline() {
		return guideline;
	}

	/**
	 * Set guideline
	 **/
	public void setGuideline(String guideline) {
		this.guideline = guideline;
	}

	public DataClassificationTagBean guideline(String guideline) {
		this.guideline = guideline;
		return this;
	}

	/**
	 * The ID of the data classification object.
	 * @return id
	 **/
	public String getId() {
		return id;
	}

	/**
	 * Set id
	 **/
	public void setId(String id) {
		this.id = id;
	}

	public DataClassificationTagBean id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * The name of the data classification object.
	 * @return name
	 **/
	public String getName() {
		return name;
	}

	/**
	 * Set name
	 **/
	public void setName(String name) {
		this.name = name;
	}

	public DataClassificationTagBean name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * The rank of the data classification object.
	 * @return rank
	 **/
	public Integer getRank() {
		return rank;
	}

	/**
	 * Set rank
	 **/
	public void setRank(Integer rank) {
		this.rank = rank;
	}

	public DataClassificationTagBean rank(Integer rank) {
		this.rank = rank;
		return this;
	}

	/**
	 * The status of the data classification object.
	 * @return status
	 **/
	public String getStatus() {
		return status;
	}

	/**
	 * Set status
	 **/
	public void setStatus(String status) {
		this.status = status;
	}

	public DataClassificationTagBean status(String status) {
		this.status = status;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class DataClassificationTagBean {\n" +
			"    color: " + toIndentedString(color) + "\n" +
			"    description: " + toIndentedString(description) + "\n" +
			"    guideline: " + toIndentedString(guideline) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"    name: " + toIndentedString(name) + "\n" +
			"    rank: " + toIndentedString(rank) + "\n" +
			"    status: " + toIndentedString(status) + "\n" +
			"}";
		return sb;
	}
}
