/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

/**
 * Details about the default workflow.
 **/

public class DefaultWorkflow {

	/**
	 * Whether a draft workflow scheme is created or updated when updating an active workflow scheme. The draft is updated with the new default workflow. Defaults to `false`.
	 **/

	private Boolean updateDraftIfNeeded;

	/**
	 * The name of the workflow to set as the default workflow.
	 **/

	private String workflow;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Whether a draft workflow scheme is created or updated when updating an active workflow scheme. The draft is updated with the new default workflow. Defaults to &#x60;false&#x60;.
	 * @return updateDraftIfNeeded
	 **/
	public Boolean getUpdateDraftIfNeeded() {
		return updateDraftIfNeeded;
	}

	/**
	 * Set updateDraftIfNeeded
	 **/
	public void setUpdateDraftIfNeeded(Boolean updateDraftIfNeeded) {
		this.updateDraftIfNeeded = updateDraftIfNeeded;
	}

	public DefaultWorkflow updateDraftIfNeeded(Boolean updateDraftIfNeeded) {
		this.updateDraftIfNeeded = updateDraftIfNeeded;
		return this;
	}

	/**
	 * The name of the workflow to set as the default workflow.
	 * @return workflow
	 **/
	public String getWorkflow() {
		return workflow;
	}

	/**
	 * Set workflow
	 **/
	public void setWorkflow(String workflow) {
		this.workflow = workflow;
	}

	public DefaultWorkflow workflow(String workflow) {
		this.workflow = workflow;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class DefaultWorkflow {\n" +
			"    updateDraftIfNeeded: " + toIndentedString(updateDraftIfNeeded) + "\n" +
			"    workflow: " + toIndentedString(workflow) + "\n" +
			"}";
		return sb;
	}
}
