/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.math.BigDecimal;


public class EntityPropertyDetails {

	/**
	 * The entity property ID.
	 **/

	private BigDecimal entityId;

	/**
	 * The entity property key.
	 **/

	private String key;

	/**
	 * The new value of the entity property.
	 **/

	private String value;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The entity property ID.
	 * @return entityId
	 **/
	public BigDecimal getEntityId() {
		return entityId;
	}

	/**
	 * Set entityId
	 **/
	public void setEntityId(BigDecimal entityId) {
		this.entityId = entityId;
	}

	public EntityPropertyDetails entityId(BigDecimal entityId) {
		this.entityId = entityId;
		return this;
	}

	/**
	 * The entity property key.
	 * @return key
	 **/
	public String getKey() {
		return key;
	}

	/**
	 * Set key
	 **/
	public void setKey(String key) {
		this.key = key;
	}

	public EntityPropertyDetails key(String key) {
		this.key = key;
		return this;
	}

	/**
	 * The new value of the entity property.
	 * @return value
	 **/
	public String getValue() {
		return value;
	}

	/**
	 * Set value
	 **/
	public void setValue(String value) {
		this.value = value;
	}

	public EntityPropertyDetails value(String value) {
		this.value = value;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class EntityPropertyDetails {\n" +
			"    entityId: " + toIndentedString(entityId) + "\n" +
			"    key: " + toIndentedString(key) + "\n" +
			"    value: " + toIndentedString(value) + "\n" +
			"}";
		return sb;
	}
}
