/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.LinkedHashSet;
import java.util.Set;


public class Error {


	private Long count;


	private Set<String> issueIdsOrKeys = null;


	private String message;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get count
	 * @return count
	 **/
	public Long getCount() {
		return count;
	}

	/**
	 * Set count
	 **/
	public void setCount(Long count) {
		this.count = count;
	}

	public Error count(Long count) {
		this.count = count;
		return this;
	}

	/**
	 * Get issueIdsOrKeys
	 * @return issueIdsOrKeys
	 **/
	public Set<String> getIssueIdsOrKeys() {
		return issueIdsOrKeys;
	}

	/**
	 * Set issueIdsOrKeys
	 **/
	public void setIssueIdsOrKeys(Set<String> issueIdsOrKeys) {
		this.issueIdsOrKeys = issueIdsOrKeys;
	}

	public Error issueIdsOrKeys(Set<String> issueIdsOrKeys) {
		this.issueIdsOrKeys = issueIdsOrKeys;
		return this;
	}

	public Error addIssueIdsOrKeysItem(String issueIdsOrKeysItem) {
		if (this.issueIdsOrKeys == null) {
			this.issueIdsOrKeys = new LinkedHashSet<>();
		}
		this.issueIdsOrKeys.add(issueIdsOrKeysItem);
		return this;
	}

	/**
	 * Get message
	 * @return message
	 **/
	public String getMessage() {
		return message;
	}

	/**
	 * Set message
	 **/
	public void setMessage(String message) {
		this.message = message;
	}

	public Error message(String message) {
		this.message = message;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class Error {\n" +
			"    count: " + toIndentedString(count) + "\n" +
			"    issueIdsOrKeys: " + toIndentedString(issueIdsOrKeys) + "\n" +
			"    message: " + toIndentedString(message) + "\n" +
			"}";
		return sb;
	}
}
