/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

/**
 * Details of a field.
 **/

public class Field {

	/**
	 * Number of contexts where the field is used.
	 **/

	private Long contextsCount;

	/**
	 * The description of the field.
	 **/

	private String description;

	/**
	 * The ID of the field.
	 **/

	private String id;

	/**
	 * Whether the field is locked.
	 **/

	private Boolean isLocked;

	/**
	 * Whether the field is shown on screen or not.
	 **/

	private Boolean isUnscreenable;

	/**
	 * The key of the field.
	 **/

	private String key;


	private FieldLastUsed lastUsed;

	/**
	 * The name of the field.
	 **/

	private String name;

	/**
	 * Number of projects where the field is used.
	 **/

	private Long projectsCount;


	private JsonTypeBean schema;

	/**
	 * Number of screens where the field is used.
	 **/

	private Long screensCount;

	/**
	 * The searcher key of the field. Returned for custom fields.
	 **/

	private String searcherKey;

	/**
	 * The stable ID of the field.
	 **/

	private String stableId;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Number of contexts where the field is used.
	 * @return contextsCount
	 **/
	public Long getContextsCount() {
		return contextsCount;
	}

	/**
	 * Set contextsCount
	 **/
	public void setContextsCount(Long contextsCount) {
		this.contextsCount = contextsCount;
	}

	public Field contextsCount(Long contextsCount) {
		this.contextsCount = contextsCount;
		return this;
	}

	/**
	 * The description of the field.
	 * @return description
	 **/
	public String getDescription() {
		return description;
	}

	/**
	 * Set description
	 **/
	public void setDescription(String description) {
		this.description = description;
	}

	public Field description(String description) {
		this.description = description;
		return this;
	}

	/**
	 * The ID of the field.
	 * @return id
	 **/
	public String getId() {
		return id;
	}

	/**
	 * Set id
	 **/
	public void setId(String id) {
		this.id = id;
	}

	public Field id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * Whether the field is locked.
	 * @return isLocked
	 **/
	public Boolean getIsLocked() {
		return isLocked;
	}

	/**
	 * Set isLocked
	 **/
	public void setIsLocked(Boolean isLocked) {
		this.isLocked = isLocked;
	}

	public Field isLocked(Boolean isLocked) {
		this.isLocked = isLocked;
		return this;
	}

	/**
	 * Whether the field is shown on screen or not.
	 * @return isUnscreenable
	 **/
	public Boolean getIsUnscreenable() {
		return isUnscreenable;
	}

	/**
	 * Set isUnscreenable
	 **/
	public void setIsUnscreenable(Boolean isUnscreenable) {
		this.isUnscreenable = isUnscreenable;
	}

	public Field isUnscreenable(Boolean isUnscreenable) {
		this.isUnscreenable = isUnscreenable;
		return this;
	}

	/**
	 * The key of the field.
	 * @return key
	 **/
	public String getKey() {
		return key;
	}

	/**
	 * Set key
	 **/
	public void setKey(String key) {
		this.key = key;
	}

	public Field key(String key) {
		this.key = key;
		return this;
	}

	/**
	 * Get lastUsed
	 * @return lastUsed
	 **/
	public FieldLastUsed getLastUsed() {
		return lastUsed;
	}

	/**
	 * Set lastUsed
	 **/
	public void setLastUsed(FieldLastUsed lastUsed) {
		this.lastUsed = lastUsed;
	}

	public Field lastUsed(FieldLastUsed lastUsed) {
		this.lastUsed = lastUsed;
		return this;
	}

	/**
	 * The name of the field.
	 * @return name
	 **/
	public String getName() {
		return name;
	}

	/**
	 * Set name
	 **/
	public void setName(String name) {
		this.name = name;
	}

	public Field name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Number of projects where the field is used.
	 * @return projectsCount
	 **/
	public Long getProjectsCount() {
		return projectsCount;
	}

	/**
	 * Set projectsCount
	 **/
	public void setProjectsCount(Long projectsCount) {
		this.projectsCount = projectsCount;
	}

	public Field projectsCount(Long projectsCount) {
		this.projectsCount = projectsCount;
		return this;
	}

	/**
	 * Get schema
	 * @return schema
	 **/
	public JsonTypeBean getSchema() {
		return schema;
	}

	/**
	 * Set schema
	 **/
	public void setSchema(JsonTypeBean schema) {
		this.schema = schema;
	}

	public Field schema(JsonTypeBean schema) {
		this.schema = schema;
		return this;
	}

	/**
	 * Number of screens where the field is used.
	 * @return screensCount
	 **/
	public Long getScreensCount() {
		return screensCount;
	}

	/**
	 * Set screensCount
	 **/
	public void setScreensCount(Long screensCount) {
		this.screensCount = screensCount;
	}

	public Field screensCount(Long screensCount) {
		this.screensCount = screensCount;
		return this;
	}

	/**
	 * The searcher key of the field. Returned for custom fields.
	 * @return searcherKey
	 **/
	public String getSearcherKey() {
		return searcherKey;
	}

	/**
	 * Set searcherKey
	 **/
	public void setSearcherKey(String searcherKey) {
		this.searcherKey = searcherKey;
	}

	public Field searcherKey(String searcherKey) {
		this.searcherKey = searcherKey;
		return this;
	}

	/**
	 * The stable ID of the field.
	 * @return stableId
	 **/
	public String getStableId() {
		return stableId;
	}

	/**
	 * Set stableId
	 **/
	public void setStableId(String stableId) {
		this.stableId = stableId;
	}

	public Field stableId(String stableId) {
		this.stableId = stableId;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class Field {\n" +
			"    contextsCount: " + toIndentedString(contextsCount) + "\n" +
			"    description: " + toIndentedString(description) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"    isLocked: " + toIndentedString(isLocked) + "\n" +
			"    isUnscreenable: " + toIndentedString(isUnscreenable) + "\n" +
			"    key: " + toIndentedString(key) + "\n" +
			"    lastUsed: " + toIndentedString(lastUsed) + "\n" +
			"    name: " + toIndentedString(name) + "\n" +
			"    projectsCount: " + toIndentedString(projectsCount) + "\n" +
			"    schema: " + toIndentedString(schema) + "\n" +
			"    screensCount: " + toIndentedString(screensCount) + "\n" +
			"    searcherKey: " + toIndentedString(searcherKey) + "\n" +
			"    stableId: " + toIndentedString(stableId) + "\n" +
			"}";
		return sb;
	}
}
