/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.atlassian.jira.v3.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.net.URL;

/**
 * The priority of the linked issue.
 */
@Data
@Builder(toBuilder = true)
@NoArgsConstructor
@AllArgsConstructor
public class FieldsPriority {
	/**
	 * The description of the issue priority.
	 */
	private String description;

	/**
	 * The URL of the icon for the issue priority.
	 */
	private String iconUrl;

	/**
	 * The ID of the issue priority.
	 */
	private String id;

	/**
	 * Whether this priority is the default.
	 */
	private Boolean isDefault;

	/**
	 * The name of the issue priority.
	 */
	private String name;

	private ExpandPrioritySchemePage schemes;

	/**
	 * The URL of the issue priority.
	 */
	private URL self;

	/**
	 * The color used to indicate the issue priority.
	 */
	private String statusColor;
}
