/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Project list with assigned field configuration schema.
 **/

public class FieldConfigurationSchemeProjects {


	private FieldConfigurationScheme fieldConfigurationScheme;

	/**
	 * The IDs of projects using the field configuration scheme.
	 **/

	private List<String> projectIds = new ArrayList<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get fieldConfigurationScheme
	 * @return fieldConfigurationScheme
	 **/
	public FieldConfigurationScheme getFieldConfigurationScheme() {
		return fieldConfigurationScheme;
	}

	/**
	 * Set fieldConfigurationScheme
	 **/
	public void setFieldConfigurationScheme(FieldConfigurationScheme fieldConfigurationScheme) {
		this.fieldConfigurationScheme = fieldConfigurationScheme;
	}

	public FieldConfigurationSchemeProjects fieldConfigurationScheme(FieldConfigurationScheme fieldConfigurationScheme) {
		this.fieldConfigurationScheme = fieldConfigurationScheme;
		return this;
	}

	/**
	 * The IDs of projects using the field configuration scheme.
	 * @return projectIds
	 **/
	public List<String> getProjectIds() {
		return projectIds;
	}

	/**
	 * Set projectIds
	 **/
	public void setProjectIds(List<String> projectIds) {
		this.projectIds = projectIds;
	}

	public FieldConfigurationSchemeProjects projectIds(List<String> projectIds) {
		this.projectIds = projectIds;
		return this;
	}

	public FieldConfigurationSchemeProjects addProjectIdsItem(String projectIdsItem) {
		if (this.projectIds == null) {
			this.projectIds = new ArrayList<>();
		}
		this.projectIds.add(projectIdsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class FieldConfigurationSchemeProjects {\n" +
			"    fieldConfigurationScheme: " + toIndentedString(fieldConfigurationScheme) + "\n" +
			"    projectIds: " + toIndentedString(projectIds) + "\n" +
			"}";
		return sb;
	}
}
