/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * A clause that asserts the current value of a field. For example, `summary ~ test`.
 **/

public class FieldValueClause {


	private JqlQueryField field;


	private JqlQueryClauseOperand operand;
	/**
	 * The operator between the field and operand.
	 **/

	private OperatorEnum operator;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get field
	 * @return field
	 **/
	public JqlQueryField getField() {
		return field;
	}

	/**
	 * Set field
	 **/
	public void setField(JqlQueryField field) {
		this.field = field;
	}

	public FieldValueClause field(JqlQueryField field) {
		this.field = field;
		return this;
	}

	/**
	 * Get operand
	 * @return operand
	 **/
	public JqlQueryClauseOperand getOperand() {
		return operand;
	}

	/**
	 * Set operand
	 **/
	public void setOperand(JqlQueryClauseOperand operand) {
		this.operand = operand;
	}

	public FieldValueClause operand(JqlQueryClauseOperand operand) {
		this.operand = operand;
		return this;
	}

	/**
	 * The operator between the field and operand.
	 * @return operator
	 **/
	public OperatorEnum getOperator() {
		return operator;
	}

	/**
	 * Set operator
	 **/
	public void setOperator(OperatorEnum operator) {
		this.operator = operator;
	}

	public FieldValueClause operator(OperatorEnum operator) {
		this.operator = operator;
		return this;
	}


	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class FieldValueClause {\n" +
			"    field: " + toIndentedString(field) + "\n" +
			"    operand: " + toIndentedString(operand) + "\n" +
			"    operator: " + toIndentedString(operator) + "\n" +
			"}";
		return sb;
	}

	public enum OperatorEnum {

		EQUAL("="), NOT_EQUAL("!="), GREATER_THAN(">"), LESS_THAN("<"), GREATER_THAN_OR_EQUAL_TO(">="), LESS_THAN_OR_EQUAL_TO("<="), IN("in"), NOT_IN("not in"), TILDE("~"), TILDE_EQUAL("~="), IS("is"), IS_NOT("is not");


		String value;

		OperatorEnum(String v) {
			value = v;
		}

		@JsonValue
		public String value() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}
	}
}
