/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import com.fasterxml.jackson.annotation.JsonValue;

import java.util.ArrayList;
import java.util.List;

/**
 * A clause that asserts whether a field was changed. For example, `status CHANGED AFTER startOfMonth(-1M)`.See [CHANGED](https://confluence.atlassian.com/x/dgiiLQ#Advancedsearching-operatorsreference-CHANGEDCHANGED) for more information about the CHANGED operator.
 **/

public class FieldChangedClause {


	private JqlQueryField field;
	/**
	 * The operator applied to the field.
	 **/

	private OperatorEnum operator;
	/**
	 * The list of time predicates.
	 **/

	private List<JqlQueryClauseTimePredicate> predicates = new ArrayList<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get field
	 * @return field
	 **/
	public JqlQueryField getField() {
		return field;
	}

	/**
	 * Set field
	 **/
	public void setField(JqlQueryField field) {
		this.field = field;
	}

	public FieldChangedClause field(JqlQueryField field) {
		this.field = field;
		return this;
	}

	/**
	 * The operator applied to the field.
	 * @return operator
	 **/
	public OperatorEnum getOperator() {
		return operator;
	}

	/**
	 * Set operator
	 **/
	public void setOperator(OperatorEnum operator) {
		this.operator = operator;
	}

	public FieldChangedClause operator(OperatorEnum operator) {
		this.operator = operator;
		return this;
	}

	/**
	 * The list of time predicates.
	 * @return predicates
	 **/
	public List<JqlQueryClauseTimePredicate> getPredicates() {
		return predicates;
	}

	/**
	 * Set predicates
	 **/
	public void setPredicates(List<JqlQueryClauseTimePredicate> predicates) {
		this.predicates = predicates;
	}

	public FieldChangedClause predicates(List<JqlQueryClauseTimePredicate> predicates) {
		this.predicates = predicates;
		return this;
	}

	public FieldChangedClause addPredicatesItem(JqlQueryClauseTimePredicate predicatesItem) {
		if (this.predicates == null) {
			this.predicates = new ArrayList<>();
		}
		this.predicates.add(predicatesItem);
		return this;
	}


	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class FieldChangedClause {\n" +
			"    field: " + toIndentedString(field) + "\n" +
			"    operator: " + toIndentedString(operator) + "\n" +
			"    predicates: " + toIndentedString(predicates) + "\n" +
			"}";
		return sb;
	}

	public enum OperatorEnum {

		CHANGED("changed");


		String value;

		OperatorEnum(String v) {
			value = v;
		}

		@JsonValue
		public String value() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}
	}
}
