/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * An operand that is a function. See [Advanced searching - functions reference](https://confluence.atlassian.com/x/dwiiLQ) for more information about JQL functions.
 **/

public class FunctionOperand {

	/**
	 * The list of function arguments.
	 **/

	private List<String> arguments = new ArrayList<>();

	/**
	 * Encoded operand, which can be used directly in a JQL query.
	 **/

	private String encodedOperand;

	/**
	 * The name of the function.
	 **/

	private String function;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The list of function arguments.
	 * @return arguments
	 **/
	public List<String> getArguments() {
		return arguments;
	}

	/**
	 * Set arguments
	 **/
	public void setArguments(List<String> arguments) {
		this.arguments = arguments;
	}

	public FunctionOperand arguments(List<String> arguments) {
		this.arguments = arguments;
		return this;
	}

	public FunctionOperand addArgumentsItem(String argumentsItem) {
		if (this.arguments == null) {
			this.arguments = new ArrayList<>();
		}
		this.arguments.add(argumentsItem);
		return this;
	}

	/**
	 * Encoded operand, which can be used directly in a JQL query.
	 * @return encodedOperand
	 **/
	public String getEncodedOperand() {
		return encodedOperand;
	}

	/**
	 * Set encodedOperand
	 **/
	public void setEncodedOperand(String encodedOperand) {
		this.encodedOperand = encodedOperand;
	}

	public FunctionOperand encodedOperand(String encodedOperand) {
		this.encodedOperand = encodedOperand;
		return this;
	}

	/**
	 * The name of the function.
	 * @return function
	 **/
	public String getFunction() {
		return function;
	}

	/**
	 * Set function
	 **/
	public void setFunction(String function) {
		this.function = function;
	}

	public FunctionOperand function(String function) {
		this.function = function;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class FunctionOperand {\n" +
			"    arguments: " + toIndentedString(arguments) + "\n" +
			"    encodedOperand: " + toIndentedString(encodedOperand) + "\n" +
			"    function: " + toIndentedString(function) + "\n" +
			"}";
		return sb;
	}
}
