/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.List;

/**
 * Result of your JQL search. Returns a list of issue IDs and a token to fetch the next page if one exists.
 **/

public class IdSearchResults {

	/**
	 * The list of issue IDs found by the search.
	 **/

	private List<Long> issueIds = null;

	/**
	 * Continuation token to fetch the next page. If this result represents the last or the only page this token will be null.
	 **/

	private String nextPageToken;

	public IdSearchResults() {
	}


	public IdSearchResults(
		List<Long> issueIds,
		String nextPageToken
	) {
		this.issueIds = issueIds;
		this.nextPageToken = nextPageToken;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The list of issue IDs found by the search.
	 * @return issueIds
	 **/
	public List<Long> getIssueIds() {
		return issueIds;
	}

	/**
	 * Continuation token to fetch the next page. If this result represents the last or the only page this token will be null.
	 * @return nextPageToken
	 **/
	public String getNextPageToken() {
		return nextPageToken;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IdSearchResults {\n" +
			"    issueIds: " + toIndentedString(issueIds) + "\n" +
			"    nextPageToken: " + toIndentedString(nextPageToken) + "\n" +
			"}";
		return sb;
	}
}
