/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

public class IdSearchRequestBean {

	/**
	 * A [JQL](https://confluence.atlassian.com/x/egORLQ) expression. Order by clauses are not allowed.
	 **/

	private String jql;

	/**
	 * The maximum number of items to return per page.
	 **/

	private Integer maxResults = 1000;

	/**
	 * The continuation token to fetch the next page. This token is provided by the response of this endpoint.
	 **/

	private String nextPageToken;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * A [JQL](https://confluence.atlassian.com/x/egORLQ) expression. Order by clauses are not allowed.
	 * @return jql
	 **/
	public String getJql() {
		return jql;
	}

	/**
	 * Set jql
	 **/
	public void setJql(String jql) {
		this.jql = jql;
	}

	public IdSearchRequestBean jql(String jql) {
		this.jql = jql;
		return this;
	}

	/**
	 * The maximum number of items to return per page.
	 * @return maxResults
	 **/
	public Integer getMaxResults() {
		return maxResults;
	}

	/**
	 * Set maxResults
	 **/
	public void setMaxResults(Integer maxResults) {
		this.maxResults = maxResults;
	}

	public IdSearchRequestBean maxResults(Integer maxResults) {
		this.maxResults = maxResults;
		return this;
	}

	/**
	 * The continuation token to fetch the next page. This token is provided by the response of this endpoint.
	 * @return nextPageToken
	 **/
	public String getNextPageToken() {
		return nextPageToken;
	}

	/**
	 * Set nextPageToken
	 **/
	public void setNextPageToken(String nextPageToken) {
		this.nextPageToken = nextPageToken;
	}

	public IdSearchRequestBean nextPageToken(String nextPageToken) {
		this.nextPageToken = nextPageToken;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IdSearchRequestBean {\n" +
			"    jql: " + toIndentedString(jql) + "\n" +
			"    maxResults: " + toIndentedString(maxResults) + "\n" +
			"    nextPageToken: " + toIndentedString(nextPageToken) + "\n" +
			"}";
		return sb;
	}
}
