/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

/**
 * Mapping of an issue type to a context.
 **/

public class IssueTypeToContextMapping {

	/**
	 * The ID of the context.
	 **/

	private String contextId;

	/**
	 * Whether the context is mapped to any issue type.
	 **/

	private Boolean isAnyIssueType;

	/**
	 * The ID of the issue type.
	 **/

	private String issueTypeId;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The ID of the context.
	 * @return contextId
	 **/
	public String getContextId() {
		return contextId;
	}

	/**
	 * Set contextId
	 **/
	public void setContextId(String contextId) {
		this.contextId = contextId;
	}

	public IssueTypeToContextMapping contextId(String contextId) {
		this.contextId = contextId;
		return this;
	}

	/**
	 * Whether the context is mapped to any issue type.
	 * @return isAnyIssueType
	 **/
	public Boolean getIsAnyIssueType() {
		return isAnyIssueType;
	}

	/**
	 * Set isAnyIssueType
	 **/
	public void setIsAnyIssueType(Boolean isAnyIssueType) {
		this.isAnyIssueType = isAnyIssueType;
	}

	public IssueTypeToContextMapping isAnyIssueType(Boolean isAnyIssueType) {
		this.isAnyIssueType = isAnyIssueType;
		return this;
	}

	/**
	 * The ID of the issue type.
	 * @return issueTypeId
	 **/
	public String getIssueTypeId() {
		return issueTypeId;
	}

	/**
	 * Set issueTypeId
	 **/
	public void setIssueTypeId(String issueTypeId) {
		this.issueTypeId = issueTypeId;
	}

	public IssueTypeToContextMapping issueTypeId(String issueTypeId) {
		this.issueTypeId = issueTypeId;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IssueTypeToContextMapping {\n" +
			"    contextId: " + toIndentedString(contextId) + "\n" +
			"    isAnyIssueType: " + toIndentedString(isAnyIssueType) + "\n" +
			"    issueTypeId: " + toIndentedString(issueTypeId) + "\n" +
			"}";
		return sb;
	}
}
