/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * List of Issue Ids Or Keys that are to be archived or unarchived
 **/

public class IssueArchivalSyncRequest {


	private List<String> issueIdsOrKeys = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get issueIdsOrKeys
	 * @return issueIdsOrKeys
	 **/
	public List<String> getIssueIdsOrKeys() {
		return issueIdsOrKeys;
	}

	/**
	 * Set issueIdsOrKeys
	 **/
	public void setIssueIdsOrKeys(List<String> issueIdsOrKeys) {
		this.issueIdsOrKeys = issueIdsOrKeys;
	}

	public IssueArchivalSyncRequest issueIdsOrKeys(List<String> issueIdsOrKeys) {
		this.issueIdsOrKeys = issueIdsOrKeys;
		return this;
	}

	public IssueArchivalSyncRequest addIssueIdsOrKeysItem(String issueIdsOrKeysItem) {
		if (this.issueIdsOrKeys == null) {
			this.issueIdsOrKeys = new ArrayList<>();
		}
		this.issueIdsOrKeys.add(issueIdsOrKeysItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IssueArchivalSyncRequest {\n" +
			"    issueIdsOrKeys: " + toIndentedString(issueIdsOrKeys) + "\n" +
			"}";
		return sb;
	}
}
