/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * A list of changelog IDs.
 **/

public class IssueChangelogIds {

	/**
	 * The list of changelog IDs.
	 **/

	private Set<Long> changelogIds = new LinkedHashSet<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The list of changelog IDs.
	 * @return changelogIds
	 **/
	public Set<Long> getChangelogIds() {
		return changelogIds;
	}

	/**
	 * Set changelogIds
	 **/
	public void setChangelogIds(Set<Long> changelogIds) {
		this.changelogIds = changelogIds;
	}

	public IssueChangelogIds changelogIds(Set<Long> changelogIds) {
		this.changelogIds = changelogIds;
		return this;
	}

	public IssueChangelogIds addChangelogIdsItem(Long changelogIdsItem) {
		if (this.changelogIds == null) {
			this.changelogIds = new LinkedHashSet<>();
		}
		this.changelogIds.add(changelogIdsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IssueChangelogIds {\n" +
			"    changelogIds: " + toIndentedString(changelogIds) + "\n" +
			"}";
		return sb;
	}
}
