/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Bulk operation filter details.
 **/

public class IssueFilterForBulkPropertyDelete {

	/**
	 * The value of properties to perform the bulk operation on.
	 **/

	private Object currentValue = null;

	/**
	 * List of issues to perform the bulk delete operation on.
	 **/

	private Set<Long> entityIds = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The value of properties to perform the bulk operation on.
	 * @return currentValue
	 **/
	public Object getCurrentValue() {
		return currentValue;
	}

	/**
	 * Set currentValue
	 **/
	public void setCurrentValue(Object currentValue) {
		this.currentValue = currentValue;
	}

	public IssueFilterForBulkPropertyDelete currentValue(Object currentValue) {
		this.currentValue = currentValue;
		return this;
	}

	/**
	 * List of issues to perform the bulk delete operation on.
	 * @return entityIds
	 **/
	public Set<Long> getEntityIds() {
		return entityIds;
	}

	/**
	 * Set entityIds
	 **/
	public void setEntityIds(Set<Long> entityIds) {
		this.entityIds = entityIds;
	}

	public IssueFilterForBulkPropertyDelete entityIds(Set<Long> entityIds) {
		this.entityIds = entityIds;
		return this;
	}

	public IssueFilterForBulkPropertyDelete addEntityIdsItem(Long entityIdsItem) {
		if (this.entityIds == null) {
			this.entityIds = new LinkedHashSet<>();
		}
		this.entityIds.add(entityIdsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IssueFilterForBulkPropertyDelete {\n" +
			"    currentValue: " + toIndentedString(currentValue) + "\n" +
			"    entityIds: " + toIndentedString(entityIds) + "\n" +
			"}";
		return sb;
	}
}
