/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.List;

/**
 * The wrapper for the issue creation metadata for a list of projects.
 **/

public class IssueCreateMetadata {

	/**
	 * Expand options that include additional project details in the response.
	 **/

	private String expand;

	/**
	 * List of projects and their issue creation metadata.
	 **/

	private List<ProjectIssueCreateMetadata> projects = null;

	public IssueCreateMetadata() {
	}


	public IssueCreateMetadata(
		String expand,
		List<ProjectIssueCreateMetadata> projects
	) {
		this.expand = expand;
		this.projects = projects;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Expand options that include additional project details in the response.
	 * @return expand
	 **/
	public String getExpand() {
		return expand;
	}

	/**
	 * List of projects and their issue creation metadata.
	 * @return projects
	 **/
	public List<ProjectIssueCreateMetadata> getProjects() {
		return projects;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IssueCreateMetadata {\n" +
			"    expand: " + toIndentedString(expand) + "\n" +
			"    projects: " + toIndentedString(projects) + "\n" +
			"}";
		return sb;
	}
}
