/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.HashMap;
import java.util.Map;

/**
 * An issue ID with entity property values. See [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/) for more information.
 **/

public class IssueEntityPropertiesForMultiUpdate {

	/**
	 * The ID of the issue.
	 **/

	private Long issueID;

	/**
	 * Entity properties to set on the issue. The maximum length of an issue property value is 32768 characters.
	 **/

	private Map<String, JsonNode> properties = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The ID of the issue.
	 * @return issueID
	 **/
	public Long getIssueID() {
		return issueID;
	}

	/**
	 * Set issueID
	 **/
	public void setIssueID(Long issueID) {
		this.issueID = issueID;
	}

	public IssueEntityPropertiesForMultiUpdate issueID(Long issueID) {
		this.issueID = issueID;
		return this;
	}

	/**
	 * Entity properties to set on the issue. The maximum length of an issue property value is 32768 characters.
	 * @return properties
	 **/
	public Map<String, JsonNode> getProperties() {
		return properties;
	}

	/**
	 * Set properties
	 **/
	public void setProperties(Map<String, JsonNode> properties) {
		this.properties = properties;
	}

	public IssueEntityPropertiesForMultiUpdate properties(Map<String, JsonNode> properties) {
		this.properties = properties;
		return this;
	}

	public IssueEntityPropertiesForMultiUpdate putPropertiesItem(String key, JsonNode propertiesItem) {
		if (this.properties == null) {
			this.properties = new HashMap<>();
		}
		this.properties.put(key, propertiesItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IssueEntityPropertiesForMultiUpdate {\n" +
			"    issueID: " + toIndentedString(issueID) + "\n" +
			"    properties: " + toIndentedString(properties) + "\n" +
			"}";
		return sb;
	}
}
