/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Details of an issue type screen scheme.
 **/
@Data
@NoArgsConstructor
@AllArgsConstructor
public class IssueTypeScreenScheme {

	/**
	 * The description of the issue type screen scheme.
	 *
	 * -- GETTER --
	 *  The description of the issue type screen scheme.
	 *
	 *
	 * -- SETTER --
	 *  Set description
	 @return description
	 */
	private String description;

	/**
	 * The ID of the issue type screen scheme.
	 *
	 * -- GETTER --
	 *  The ID of the issue type screen scheme.
	 *
	 *
	 * -- SETTER --
	 *  Set id
	 @return id
	 */
	private String id;

	/**
	 * The name of the issue type screen scheme.
	 *
	 * -- GETTER --
	 *  The name of the issue type screen scheme.
	 *
	 *
	 * -- SETTER --
	 *  Set name
	 @return name
	 */
	private String name;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public IssueTypeScreenScheme description(String description) {
		this.description = description;
		return this;
	}

	public IssueTypeScreenScheme id(String id) {
		this.id = id;
		return this;
	}

	public IssueTypeScreenScheme name(String name) {
		this.name = name;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IssueTypeScreenScheme {\n" +
			"    description: " + toIndentedString(description) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"    name: " + toIndentedString(name) + "\n" +
			"}";
		return sb;
	}
}
