/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Issue type screen scheme with a list of the projects that use it.
 **/

public class IssueTypeScreenSchemesProjects {


	private IssueTypeScreenScheme issueTypeScreenScheme;

	/**
	 * The IDs of the projects using the issue type screen scheme.
	 **/

	private List<String> projectIds = new ArrayList<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get issueTypeScreenScheme
	 * @return issueTypeScreenScheme
	 **/
	public IssueTypeScreenScheme getIssueTypeScreenScheme() {
		return issueTypeScreenScheme;
	}

	/**
	 * Set issueTypeScreenScheme
	 **/
	public void setIssueTypeScreenScheme(IssueTypeScreenScheme issueTypeScreenScheme) {
		this.issueTypeScreenScheme = issueTypeScreenScheme;
	}

	public IssueTypeScreenSchemesProjects issueTypeScreenScheme(IssueTypeScreenScheme issueTypeScreenScheme) {
		this.issueTypeScreenScheme = issueTypeScreenScheme;
		return this;
	}

	/**
	 * The IDs of the projects using the issue type screen scheme.
	 * @return projectIds
	 **/
	public List<String> getProjectIds() {
		return projectIds;
	}

	/**
	 * Set projectIds
	 **/
	public void setProjectIds(List<String> projectIds) {
		this.projectIds = projectIds;
	}

	public IssueTypeScreenSchemesProjects projectIds(List<String> projectIds) {
		this.projectIds = projectIds;
		return this;
	}

	public IssueTypeScreenSchemesProjects addProjectIdsItem(String projectIdsItem) {
		if (this.projectIds == null) {
			this.projectIds = new ArrayList<>();
		}
		this.projectIds.add(projectIdsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class IssueTypeScreenSchemesProjects {\n" +
			"    issueTypeScreenScheme: " + toIndentedString(issueTypeScreenScheme) + "\n" +
			"    projectIds: " + toIndentedString(projectIds) + "\n" +
			"}";
		return sb;
	}
}
