/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Details of the order-by JQL clause.
 **/

public class JqlQueryOrderByClause {

	/**
	 * The list of order-by clause fields and their ordering directives.
	 **/

	private List<JqlQueryOrderByClauseElement> fields = new ArrayList<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The list of order-by clause fields and their ordering directives.
	 * @return fields
	 **/
	public List<JqlQueryOrderByClauseElement> getFields() {
		return fields;
	}

	/**
	 * Set fields
	 **/
	public void setFields(List<JqlQueryOrderByClauseElement> fields) {
		this.fields = fields;
	}

	public JqlQueryOrderByClause fields(List<JqlQueryOrderByClauseElement> fields) {
		this.fields = fields;
		return this;
	}

	public JqlQueryOrderByClause addFieldsItem(JqlQueryOrderByClauseElement fieldsItem) {
		if (this.fields == null) {
			this.fields = new ArrayList<>();
		}
		this.fields.add(fieldsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class JqlQueryOrderByClause {\n" +
			"    fields: " + toIndentedString(fields) + "\n" +
			"}";
		return sb;
	}
}
