/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Lists of JQL reference data.
 **/

public class JQLReferenceData {

	/**
	 * List of JQL query reserved words.
	 **/

	private List<String> jqlReservedWords = null;

	/**
	 * List of fields usable in JQL queries.
	 **/

	private List<FieldReferenceData> visibleFieldNames = null;

	/**
	 * List of functions usable in JQL queries.
	 **/

	private List<FunctionReferenceData> visibleFunctionNames = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * List of JQL query reserved words.
	 * @return jqlReservedWords
	 **/
	public List<String> getJqlReservedWords() {
		return jqlReservedWords;
	}

	/**
	 * Set jqlReservedWords
	 **/
	public void setJqlReservedWords(List<String> jqlReservedWords) {
		this.jqlReservedWords = jqlReservedWords;
	}

	public JQLReferenceData jqlReservedWords(List<String> jqlReservedWords) {
		this.jqlReservedWords = jqlReservedWords;
		return this;
	}

	public JQLReferenceData addJqlReservedWordsItem(String jqlReservedWordsItem) {
		if (this.jqlReservedWords == null) {
			this.jqlReservedWords = new ArrayList<>();
		}
		this.jqlReservedWords.add(jqlReservedWordsItem);
		return this;
	}

	/**
	 * List of fields usable in JQL queries.
	 * @return visibleFieldNames
	 **/
	public List<FieldReferenceData> getVisibleFieldNames() {
		return visibleFieldNames;
	}

	/**
	 * Set visibleFieldNames
	 **/
	public void setVisibleFieldNames(List<FieldReferenceData> visibleFieldNames) {
		this.visibleFieldNames = visibleFieldNames;
	}

	public JQLReferenceData visibleFieldNames(List<FieldReferenceData> visibleFieldNames) {
		this.visibleFieldNames = visibleFieldNames;
		return this;
	}

	public JQLReferenceData addVisibleFieldNamesItem(FieldReferenceData visibleFieldNamesItem) {
		if (this.visibleFieldNames == null) {
			this.visibleFieldNames = new ArrayList<>();
		}
		this.visibleFieldNames.add(visibleFieldNamesItem);
		return this;
	}

	/**
	 * List of functions usable in JQL queries.
	 * @return visibleFunctionNames
	 **/
	public List<FunctionReferenceData> getVisibleFunctionNames() {
		return visibleFunctionNames;
	}

	/**
	 * Set visibleFunctionNames
	 **/
	public void setVisibleFunctionNames(List<FunctionReferenceData> visibleFunctionNames) {
		this.visibleFunctionNames = visibleFunctionNames;
	}

	public JQLReferenceData visibleFunctionNames(List<FunctionReferenceData> visibleFunctionNames) {
		this.visibleFunctionNames = visibleFunctionNames;
		return this;
	}

	public JQLReferenceData addVisibleFunctionNamesItem(FunctionReferenceData visibleFunctionNamesItem) {
		if (this.visibleFunctionNames == null) {
			this.visibleFunctionNames = new ArrayList<>();
		}
		this.visibleFunctionNames.add(visibleFunctionNamesItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class JQLReferenceData {\n" +
			"    jqlReservedWords: " + toIndentedString(jqlReservedWords) + "\n" +
			"    visibleFieldNames: " + toIndentedString(visibleFieldNames) + "\n" +
			"    visibleFunctionNames: " + toIndentedString(visibleFunctionNames) + "\n" +
			"}";
		return sb;
	}
}
