/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

public class LinkIssueRequestJsonBean {


	private Comment comment;


	private LinkedIssue inwardIssue;


	private LinkedIssue outwardIssue;


	private IssueLinkType type;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get comment
	 * @return comment
	 **/
	public Comment getComment() {
		return comment;
	}

	/**
	 * Set comment
	 **/
	public void setComment(Comment comment) {
		this.comment = comment;
	}

	public LinkIssueRequestJsonBean comment(Comment comment) {
		this.comment = comment;
		return this;
	}

	/**
	 * Get inwardIssue
	 * @return inwardIssue
	 **/
	public LinkedIssue getInwardIssue() {
		return inwardIssue;
	}

	/**
	 * Set inwardIssue
	 **/
	public void setInwardIssue(LinkedIssue inwardIssue) {
		this.inwardIssue = inwardIssue;
	}

	public LinkIssueRequestJsonBean inwardIssue(LinkedIssue inwardIssue) {
		this.inwardIssue = inwardIssue;
		return this;
	}

	/**
	 * Get outwardIssue
	 * @return outwardIssue
	 **/
	public LinkedIssue getOutwardIssue() {
		return outwardIssue;
	}

	/**
	 * Set outwardIssue
	 **/
	public void setOutwardIssue(LinkedIssue outwardIssue) {
		this.outwardIssue = outwardIssue;
	}

	public LinkIssueRequestJsonBean outwardIssue(LinkedIssue outwardIssue) {
		this.outwardIssue = outwardIssue;
		return this;
	}

	/**
	 * Get type
	 * @return type
	 **/
	public IssueLinkType getType() {
		return type;
	}

	/**
	 * Set type
	 **/
	public void setType(IssueLinkType type) {
		this.type = type;
	}

	public LinkIssueRequestJsonBean type(IssueLinkType type) {
		this.type = type;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class LinkIssueRequestJsonBean {\n" +
			"    comment: " + toIndentedString(comment) + "\n" +
			"    inwardIssue: " + toIndentedString(inwardIssue) + "\n" +
			"    outwardIssue: " + toIndentedString(outwardIssue) + "\n" +
			"    type: " + toIndentedString(type) + "\n" +
			"}";
		return sb;
	}
}
