/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import com.fasterxml.jackson.annotation.JsonValue;

import java.net.URI;


public class MoveFieldBean {

	/**
	 * The ID of the screen tab field after which to place the moved screen tab field. Required if `position` isn't provided.
	 **/

	private URI after;
	/**
	 * The named position to which the screen tab field should be moved. Required if `after` isn't provided.
	 **/

	private PositionEnum position;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The ID of the screen tab field after which to place the moved screen tab field. Required if &#x60;position&#x60; isn&#39;t provided.
	 * @return after
	 **/
	public URI getAfter() {
		return after;
	}

	/**
	 * Set after
	 **/
	public void setAfter(URI after) {
		this.after = after;
	}

	public MoveFieldBean after(URI after) {
		this.after = after;
		return this;
	}

	/**
	 * The named position to which the screen tab field should be moved. Required if &#x60;after&#x60; isn&#39;t provided.
	 * @return position
	 **/
	public PositionEnum getPosition() {
		return position;
	}

	/**
	 * Set position
	 **/
	public void setPosition(PositionEnum position) {
		this.position = position;
	}

	public MoveFieldBean position(PositionEnum position) {
		this.position = position;
		return this;
	}


	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class MoveFieldBean {\n" +
			"    after: " + toIndentedString(after) + "\n" +
			"    position: " + toIndentedString(position) + "\n" +
			"}";
		return sb;
	}

	public enum PositionEnum {

		EARLIER("Earlier"), LATER("Later"), FIRST("First"), LAST("Last");


		String value;

		PositionEnum(String v) {
			value = v;
		}

		@JsonValue
		public String value() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}
	}
}
