/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * A list of issues and their respective properties to set or update. See [Entity properties](https://developer.atlassian.com/cloud/jira/platform/jira-entity-properties/) for more information.
 **/

public class MultiIssueEntityProperties {

	/**
	 * A list of issue IDs and their respective properties.
	 **/

	private List<IssueEntityPropertiesForMultiUpdate> issues = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * A list of issue IDs and their respective properties.
	 * @return issues
	 **/
	public List<IssueEntityPropertiesForMultiUpdate> getIssues() {
		return issues;
	}

	/**
	 * Set issues
	 **/
	public void setIssues(List<IssueEntityPropertiesForMultiUpdate> issues) {
		this.issues = issues;
	}

	public MultiIssueEntityProperties issues(List<IssueEntityPropertiesForMultiUpdate> issues) {
		this.issues = issues;
		return this;
	}

	public MultiIssueEntityProperties addIssuesItem(IssueEntityPropertiesForMultiUpdate issuesItem) {
		if (this.issues == null) {
			this.issues = new ArrayList<>();
		}
		this.issues.add(issuesItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class MultiIssueEntityProperties {\n" +
			"    issues: " + toIndentedString(issues) + "\n" +
			"}";
		return sb;
	}
}
