/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

public class NotificationSchemeAndProjectMappingJsonBean {


	private String notificationSchemeId;


	private String projectId;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get notificationSchemeId
	 * @return notificationSchemeId
	 **/
	public String getNotificationSchemeId() {
		return notificationSchemeId;
	}

	/**
	 * Set notificationSchemeId
	 **/
	public void setNotificationSchemeId(String notificationSchemeId) {
		this.notificationSchemeId = notificationSchemeId;
	}

	public NotificationSchemeAndProjectMappingJsonBean notificationSchemeId(String notificationSchemeId) {
		this.notificationSchemeId = notificationSchemeId;
		return this;
	}

	/**
	 * Get projectId
	 * @return projectId
	 **/
	public String getProjectId() {
		return projectId;
	}

	/**
	 * Set projectId
	 **/
	public void setProjectId(String projectId) {
		this.projectId = projectId;
	}

	public NotificationSchemeAndProjectMappingJsonBean projectId(String projectId) {
		this.projectId = projectId;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class NotificationSchemeAndProjectMappingJsonBean {\n" +
			"    notificationSchemeId: " + toIndentedString(notificationSchemeId) + "\n" +
			"    projectId: " + toIndentedString(projectId) + "\n" +
			"}";
		return sb;
	}
}
