/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

/**
 * Details of the users and groups to receive the notification.
 **/

public class NotificationRecipients extends HashMap<String, Object> {

	/**
	 * Whether the notification should be sent to the issue's assignees.
	 **/

	private Boolean assignee;

	/**
	 * List of groupIds to receive the notification.
	 **/

	private List<String> groupIds = null;

	/**
	 * List of groups to receive the notification.
	 **/

	private List<GroupName> groups = null;

	/**
	 * Whether the notification should be sent to the issue's reporter.
	 **/

	private Boolean reporter;

	/**
	 * List of users to receive the notification.
	 **/

	private List<UserDetails> users = null;

	/**
	 * Whether the notification should be sent to the issue's voters.
	 **/

	private Boolean voters;

	/**
	 * Whether the notification should be sent to the issue's watchers.
	 **/

	private Boolean watchers;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Whether the notification should be sent to the issue&#39;s assignees.
	 * @return assignee
	 **/
	public Boolean getAssignee() {
		return assignee;
	}

	/**
	 * Set assignee
	 **/
	public void setAssignee(Boolean assignee) {
		this.assignee = assignee;
	}

	public NotificationRecipients assignee(Boolean assignee) {
		this.assignee = assignee;
		return this;
	}

	/**
	 * List of groupIds to receive the notification.
	 * @return groupIds
	 **/
	public List<String> getGroupIds() {
		return groupIds;
	}

	/**
	 * Set groupIds
	 **/
	public void setGroupIds(List<String> groupIds) {
		this.groupIds = groupIds;
	}

	public NotificationRecipients groupIds(List<String> groupIds) {
		this.groupIds = groupIds;
		return this;
	}

	public NotificationRecipients addGroupIdsItem(String groupIdsItem) {
		if (this.groupIds == null) {
			this.groupIds = new ArrayList<>();
		}
		this.groupIds.add(groupIdsItem);
		return this;
	}

	/**
	 * List of groups to receive the notification.
	 * @return groups
	 **/
	public List<GroupName> getGroups() {
		return groups;
	}

	/**
	 * Set groups
	 **/
	public void setGroups(List<GroupName> groups) {
		this.groups = groups;
	}

	public NotificationRecipients groups(List<GroupName> groups) {
		this.groups = groups;
		return this;
	}

	public NotificationRecipients addGroupsItem(GroupName groupsItem) {
		if (this.groups == null) {
			this.groups = new ArrayList<>();
		}
		this.groups.add(groupsItem);
		return this;
	}

	/**
	 * Whether the notification should be sent to the issue&#39;s reporter.
	 * @return reporter
	 **/
	public Boolean getReporter() {
		return reporter;
	}

	/**
	 * Set reporter
	 **/
	public void setReporter(Boolean reporter) {
		this.reporter = reporter;
	}

	public NotificationRecipients reporter(Boolean reporter) {
		this.reporter = reporter;
		return this;
	}

	/**
	 * List of users to receive the notification.
	 * @return users
	 **/
	public List<UserDetails> getUsers() {
		return users;
	}

	/**
	 * Set users
	 **/
	public void setUsers(List<UserDetails> users) {
		this.users = users;
	}

	public NotificationRecipients users(List<UserDetails> users) {
		this.users = users;
		return this;
	}

	public NotificationRecipients addUsersItem(UserDetails usersItem) {
		if (this.users == null) {
			this.users = new ArrayList<>();
		}
		this.users.add(usersItem);
		return this;
	}

	/**
	 * Whether the notification should be sent to the issue&#39;s voters.
	 * @return voters
	 **/
	public Boolean getVoters() {
		return voters;
	}

	/**
	 * Set voters
	 **/
	public void setVoters(Boolean voters) {
		this.voters = voters;
	}

	public NotificationRecipients voters(Boolean voters) {
		this.voters = voters;
		return this;
	}

	/**
	 * Whether the notification should be sent to the issue&#39;s watchers.
	 * @return watchers
	 **/
	public Boolean getWatchers() {
		return watchers;
	}

	/**
	 * Set watchers
	 **/
	public void setWatchers(Boolean watchers) {
		this.watchers = watchers;
	}

	public NotificationRecipients watchers(Boolean watchers) {
		this.watchers = watchers;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {
		String sb = "class NotificationRecipients {\n" +
			"    " + toIndentedString(super.toString()) + "\n" +
			"    assignee: " + toIndentedString(assignee) + "\n" +
			"    groupIds: " + toIndentedString(groupIds) + "\n" +
			"    groups: " + toIndentedString(groups) + "\n" +
			"    reporter: " + toIndentedString(reporter) + "\n" +
			"    users: " + toIndentedString(users) + "\n" +
			"    voters: " + toIndentedString(voters) + "\n" +
			"    watchers: " + toIndentedString(watchers) + "\n" +
			"}";
		return sb;
	}
}
