/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

public class OperationMessage {

	/**
	 * The human-readable message that describes the result.
	 **/

	private String message;

	/**
	 * The status code of the response.
	 **/

	private Integer statusCode;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The human-readable message that describes the result.
	 * @return message
	 **/
	public String getMessage() {
		return message;
	}

	/**
	 * Set message
	 **/
	public void setMessage(String message) {
		this.message = message;
	}

	public OperationMessage message(String message) {
		this.message = message;
		return this;
	}

	/**
	 * The status code of the response.
	 * @return statusCode
	 **/
	public Integer getStatusCode() {
		return statusCode;
	}

	/**
	 * Set statusCode
	 **/
	public void setStatusCode(Integer statusCode) {
		this.statusCode = statusCode;
	}

	public OperationMessage statusCode(Integer statusCode) {
		this.statusCode = statusCode;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class OperationMessage {\n" +
			"    message: " + toIndentedString(message) + "\n" +
			"    statusCode: " + toIndentedString(statusCode) + "\n" +
			"}";
		return sb;
	}
}
