/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;


public class PageOfStatuses {

	/**
	 * Whether this is the last page.
	 **/

	private Boolean isLast;

	/**
	 * The maximum number of items that could be returned.
	 **/

	private Integer maxResults;

	/**
	 * The URL of the next page of results, if any.
	 **/

	private String nextPage;

	/**
	 * The URL of this page.
	 **/

	private String self;

	/**
	 * The index of the first item returned on the page.
	 **/

	private Long startAt;

	/**
	 * Number of items that satisfy the search.
	 **/

	private Long total;

	/**
	 * The list of items.
	 **/

	private List<JiraStatus> values = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Whether this is the last page.
	 * @return isLast
	 **/
	public Boolean getIsLast() {
		return isLast;
	}

	/**
	 * Set isLast
	 **/
	public void setIsLast(Boolean isLast) {
		this.isLast = isLast;
	}

	public PageOfStatuses isLast(Boolean isLast) {
		this.isLast = isLast;
		return this;
	}

	/**
	 * The maximum number of items that could be returned.
	 * @return maxResults
	 **/
	public Integer getMaxResults() {
		return maxResults;
	}

	/**
	 * Set maxResults
	 **/
	public void setMaxResults(Integer maxResults) {
		this.maxResults = maxResults;
	}

	public PageOfStatuses maxResults(Integer maxResults) {
		this.maxResults = maxResults;
		return this;
	}

	/**
	 * The URL of the next page of results, if any.
	 * @return nextPage
	 **/
	public String getNextPage() {
		return nextPage;
	}

	/**
	 * Set nextPage
	 **/
	public void setNextPage(String nextPage) {
		this.nextPage = nextPage;
	}

	public PageOfStatuses nextPage(String nextPage) {
		this.nextPage = nextPage;
		return this;
	}

	/**
	 * The URL of this page.
	 * @return self
	 **/
	public String getSelf() {
		return self;
	}

	/**
	 * Set self
	 **/
	public void setSelf(String self) {
		this.self = self;
	}

	public PageOfStatuses self(String self) {
		this.self = self;
		return this;
	}

	/**
	 * The index of the first item returned on the page.
	 * @return startAt
	 **/
	public Long getStartAt() {
		return startAt;
	}

	/**
	 * Set startAt
	 **/
	public void setStartAt(Long startAt) {
		this.startAt = startAt;
	}

	public PageOfStatuses startAt(Long startAt) {
		this.startAt = startAt;
		return this;
	}

	/**
	 * Number of items that satisfy the search.
	 * @return total
	 **/
	public Long getTotal() {
		return total;
	}

	/**
	 * Set total
	 **/
	public void setTotal(Long total) {
		this.total = total;
	}

	public PageOfStatuses total(Long total) {
		this.total = total;
		return this;
	}

	/**
	 * The list of items.
	 * @return values
	 **/
	public List<JiraStatus> getValues() {
		return values;
	}

	/**
	 * Set values
	 **/
	public void setValues(List<JiraStatus> values) {
		this.values = values;
	}

	public PageOfStatuses values(List<JiraStatus> values) {
		this.values = values;
		return this;
	}

	public PageOfStatuses addValuesItem(JiraStatus valuesItem) {
		if (this.values == null) {
			this.values = new ArrayList<>();
		}
		this.values.add(valuesItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class PageOfStatuses {\n" +
			"    isLast: " + toIndentedString(isLast) + "\n" +
			"    maxResults: " + toIndentedString(maxResults) + "\n" +
			"    nextPage: " + toIndentedString(nextPage) + "\n" +
			"    self: " + toIndentedString(self) + "\n" +
			"    startAt: " + toIndentedString(startAt) + "\n" +
			"    total: " + toIndentedString(total) + "\n" +
			"    values: " + toIndentedString(values) + "\n" +
			"}";
		return sb;
	}
}
