/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * A list of parsed JQL queries.
 **/

public class ParsedJqlQueries {

	/**
	 * A list of parsed JQL queries.
	 **/

	private List<ParsedJqlQuery> queries = new ArrayList<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * A list of parsed JQL queries.
	 * @return queries
	 **/
	public List<ParsedJqlQuery> getQueries() {
		return queries;
	}

	/**
	 * Set queries
	 **/
	public void setQueries(List<ParsedJqlQuery> queries) {
		this.queries = queries;
	}

	public ParsedJqlQueries queries(List<ParsedJqlQuery> queries) {
		this.queries = queries;
		return this;
	}

	public ParsedJqlQueries addQueriesItem(ParsedJqlQuery queriesItem) {
		if (this.queries == null) {
			this.queries = new ArrayList<>();
		}
		this.queries.add(queriesItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class ParsedJqlQueries {\n" +
			"    queries: " + toIndentedString(queries) + "\n" +
			"}";
		return sb;
	}
}
