/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.HashMap;
import java.util.List;
import java.util.Map;


public class ProjectRoleActorsUpdateBean {

	/**
	 * The actors to add to the project role.  Add groups using:   *  `atlassian-group-role-actor` and a list of group names.  *  `atlassian-group-role-actor-id` and a list of group IDs.  As a group's name can change, use of `atlassian-group-role-actor-id` is recommended. For example, `\"atlassian-group-role-actor-id\":[\"eef79f81-0b89-4fca-a736-4be531a10869\",\"77f6ab39-e755-4570-a6ae-2d7a8df0bcb8\"]`.  Add users using `atlassian-user-role-actor` and a list of account IDs. For example, `\"atlassian-user-role-actor\":[\"12345678-9abc-def1-2345-6789abcdef12\", \"abcdef12-3456-789a-bcde-f123456789ab\"]`.
	 **/

	private Map<String, List<String>> categorisedActors = null;

	/**
	 * The ID of the project role. Use [Get all project roles](#api-rest-api-3-role-get) to get a list of project role IDs.
	 **/

	private Long id;

	public ProjectRoleActorsUpdateBean() {
	}


	public ProjectRoleActorsUpdateBean(
		Long id
	) {
		this.id = id;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The actors to add to the project role.  Add groups using:   *  &#x60;atlassian-group-role-actor&#x60; and a list of group names.  *  &#x60;atlassian-group-role-actor-id&#x60; and a list of group IDs.  As a group&#39;s name can change, use of &#x60;atlassian-group-role-actor-id&#x60; is recommended. For example, &#x60;\&quot;atlassian-group-role-actor-id\&quot;:[\&quot;eef79f81-0b89-4fca-a736-4be531a10869\&quot;,\&quot;77f6ab39-e755-4570-a6ae-2d7a8df0bcb8\&quot;]&#x60;.  Add users using &#x60;atlassian-user-role-actor&#x60; and a list of account IDs. For example, &#x60;\&quot;atlassian-user-role-actor\&quot;:[\&quot;12345678-9abc-def1-2345-6789abcdef12\&quot;, \&quot;abcdef12-3456-789a-bcde-f123456789ab\&quot;]&#x60;.
	 * @return categorisedActors
	 **/
	public Map<String, List<String>> getCategorisedActors() {
		return categorisedActors;
	}

	/**
	 * Set categorisedActors
	 **/
	public void setCategorisedActors(Map<String, List<String>> categorisedActors) {
		this.categorisedActors = categorisedActors;
	}

	public ProjectRoleActorsUpdateBean categorisedActors(Map<String, List<String>> categorisedActors) {
		this.categorisedActors = categorisedActors;
		return this;
	}

	public ProjectRoleActorsUpdateBean putCategorisedActorsItem(String key, List<String> categorisedActorsItem) {
		if (this.categorisedActors == null) {
			this.categorisedActors = new HashMap<>();
		}
		this.categorisedActors.put(key, categorisedActorsItem);
		return this;
	}

	/**
	 * The ID of the project role. Use [Get all project roles](#api-rest-api-3-role-get) to get a list of project role IDs.
	 * @return id
	 **/
	public Long getId() {
		return id;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class ProjectRoleActorsUpdateBean {\n" +
			"    categorisedActors: " + toIndentedString(categorisedActors) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"}";
		return sb;
	}
}
