/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.HashMap;

/**
 * The linked item.
 **/

public class RemoteObject extends HashMap<String, Object> {


	private Icon icon;


	private Status status;

	/**
	 * The summary details of the item.
	 **/

	private String summary;

	/**
	 * The title of the item.
	 **/

	private String title;

	/**
	 * The URL of the item.
	 **/

	private String url;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get icon
	 * @return icon
	 **/
	public Icon getIcon() {
		return icon;
	}

	/**
	 * Set icon
	 **/
	public void setIcon(Icon icon) {
		this.icon = icon;
	}

	public RemoteObject icon(Icon icon) {
		this.icon = icon;
		return this;
	}

	/**
	 * Get status
	 * @return status
	 **/
	public Status getStatus() {
		return status;
	}

	/**
	 * Set status
	 **/
	public void setStatus(Status status) {
		this.status = status;
	}

	public RemoteObject status(Status status) {
		this.status = status;
		return this;
	}

	/**
	 * The summary details of the item.
	 * @return summary
	 **/
	public String getSummary() {
		return summary;
	}

	/**
	 * Set summary
	 **/
	public void setSummary(String summary) {
		this.summary = summary;
	}

	public RemoteObject summary(String summary) {
		this.summary = summary;
		return this;
	}

	/**
	 * The title of the item.
	 * @return title
	 **/
	public String getTitle() {
		return title;
	}

	/**
	 * Set title
	 **/
	public void setTitle(String title) {
		this.title = title;
	}

	public RemoteObject title(String title) {
		this.title = title;
		return this;
	}

	/**
	 * The URL of the item.
	 * @return url
	 **/
	public String getUrl() {
		return url;
	}

	/**
	 * Set url
	 **/
	public void setUrl(String url) {
		this.url = url;
	}

	public RemoteObject url(String url) {
		this.url = url;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {
		String sb = "class RemoteObject {\n" +
			"    " + toIndentedString(super.toString()) + "\n" +
			"    icon: " + toIndentedString(icon) + "\n" +
			"    status: " + toIndentedString(status) + "\n" +
			"    summary: " + toIndentedString(summary) + "\n" +
			"    title: " + toIndentedString(title) + "\n" +
			"    url: " + toIndentedString(url) + "\n" +
			"}";
		return sb;
	}
}
