/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

/**
 * A rule configuration.
 **/

public class RuleConfiguration {

	/**
	 * Whether the rule is disabled.
	 **/

	private Boolean disabled = false;

	/**
	 * A tag used to filter rules in [Get workflow transition rule configurations](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflow-transition-rules/#api-rest-api-3-workflow-rule-config-get).
	 **/

	private String tag;

	/**
	 * Configuration of the rule, as it is stored by the Connect or the Forge app on the rule configuration page.
	 **/

	private String value;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Whether the rule is disabled.
	 * @return disabled
	 **/
	public Boolean getDisabled() {
		return disabled;
	}

	/**
	 * Set disabled
	 **/
	public void setDisabled(Boolean disabled) {
		this.disabled = disabled;
	}

	public RuleConfiguration disabled(Boolean disabled) {
		this.disabled = disabled;
		return this;
	}

	/**
	 * A tag used to filter rules in [Get workflow transition rule configurations](https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-workflow-transition-rules/#api-rest-api-3-workflow-rule-config-get).
	 * @return tag
	 **/
	public String getTag() {
		return tag;
	}

	/**
	 * Set tag
	 **/
	public void setTag(String tag) {
		this.tag = tag;
	}

	public RuleConfiguration tag(String tag) {
		this.tag = tag;
		return this;
	}

	/**
	 * Configuration of the rule, as it is stored by the Connect or the Forge app on the rule configuration page.
	 * @return value
	 **/
	public String getValue() {
		return value;
	}

	/**
	 * Set value
	 **/
	public void setValue(String value) {
		this.value = value;
	}

	public RuleConfiguration value(String value) {
		this.value = value;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class RuleConfiguration {\n" +
			"    disabled: " + toIndentedString(disabled) + "\n" +
			"    tag: " + toIndentedString(tag) + "\n" +
			"    value: " + toIndentedString(value) + "\n" +
			"}";
		return sb;
	}
}
