/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

/**
 * Details of the sanitized JQL query.
 **/

public class SanitizedJqlQuery {

	/**
	 * The account ID of the user for whom sanitization was performed.
	 **/

	private String accountId;


	private ErrorCollection errors;

	/**
	 * The initial query.
	 **/

	private String initialQuery;

	/**
	 * The sanitized query, if there were no errors.
	 **/

	private String sanitizedQuery;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The account ID of the user for whom sanitization was performed.
	 * @return accountId
	 **/
	public String getAccountId() {
		return accountId;
	}

	/**
	 * Set accountId
	 **/
	public void setAccountId(String accountId) {
		this.accountId = accountId;
	}

	public SanitizedJqlQuery accountId(String accountId) {
		this.accountId = accountId;
		return this;
	}

	/**
	 * Get errors
	 * @return errors
	 **/
	public ErrorCollection getErrors() {
		return errors;
	}

	/**
	 * Set errors
	 **/
	public void setErrors(ErrorCollection errors) {
		this.errors = errors;
	}

	public SanitizedJqlQuery errors(ErrorCollection errors) {
		this.errors = errors;
		return this;
	}

	/**
	 * The initial query.
	 * @return initialQuery
	 **/
	public String getInitialQuery() {
		return initialQuery;
	}

	/**
	 * Set initialQuery
	 **/
	public void setInitialQuery(String initialQuery) {
		this.initialQuery = initialQuery;
	}

	public SanitizedJqlQuery initialQuery(String initialQuery) {
		this.initialQuery = initialQuery;
		return this;
	}

	/**
	 * The sanitized query, if there were no errors.
	 * @return sanitizedQuery
	 **/
	public String getSanitizedQuery() {
		return sanitizedQuery;
	}

	/**
	 * Set sanitizedQuery
	 **/
	public void setSanitizedQuery(String sanitizedQuery) {
		this.sanitizedQuery = sanitizedQuery;
	}

	public SanitizedJqlQuery sanitizedQuery(String sanitizedQuery) {
		this.sanitizedQuery = sanitizedQuery;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class SanitizedJqlQuery {\n" +
			"    accountId: " + toIndentedString(accountId) + "\n" +
			"    errors: " + toIndentedString(errors) + "\n" +
			"    initialQuery: " + toIndentedString(initialQuery) + "\n" +
			"    sanitizedQuery: " + toIndentedString(sanitizedQuery) + "\n" +
			"}";
		return sb;
	}
}
