/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.List;
import java.util.Map;

/**
 * The result of a JQL search.
 **/

public class SearchResults {

	/**
	 * Expand options that include additional search result details in the response.
	 **/

	private String expand;

	/**
	 * The list of issues found by the search.
	 **/

	private List<IssueBean> issues = null;

	/**
	 * The maximum number of results that could be on the page.
	 **/

	private Integer maxResults;

	/**
	 * The ID and name of each field in the search results.
	 **/

	private Map<String, String> names = null;

	/**
	 * The schema describing the field types in the search results.
	 **/

	private Map<String, JsonTypeBean> schema = null;

	/**
	 * The index of the first item returned on the page.
	 **/

	private Integer startAt;

	/**
	 * The number of results on the page.
	 **/

	private Integer total;

	/**
	 * Any warnings related to the JQL query.
	 **/

	private List<String> warningMessages = null;

	public SearchResults() {
	}


	public SearchResults(
		String expand,
		List<IssueBean> issues,
		Integer maxResults,
		Map<String, String> names,
		Map<String, JsonTypeBean> schema,
		Integer startAt,
		Integer total,
		List<String> warningMessages
	) {
		this.expand = expand;
		this.issues = issues;
		this.maxResults = maxResults;
		this.names = names;
		this.schema = schema;
		this.startAt = startAt;
		this.total = total;
		this.warningMessages = warningMessages;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Expand options that include additional search result details in the response.
	 * @return expand
	 **/
	public String getExpand() {
		return expand;
	}

	/**
	 * The list of issues found by the search.
	 * @return issues
	 **/
	public List<IssueBean> getIssues() {
		return issues;
	}

	/**
	 * The maximum number of results that could be on the page.
	 * @return maxResults
	 **/
	public Integer getMaxResults() {
		return maxResults;
	}

	/**
	 * The ID and name of each field in the search results.
	 * @return names
	 **/
	public Map<String, String> getNames() {
		return names;
	}

	/**
	 * The schema describing the field types in the search results.
	 * @return schema
	 **/
	public Map<String, JsonTypeBean> getSchema() {
		return schema;
	}

	/**
	 * The index of the first item returned on the page.
	 * @return startAt
	 **/
	public Integer getStartAt() {
		return startAt;
	}

	/**
	 * The number of results on the page.
	 * @return total
	 **/
	public Integer getTotal() {
		return total;
	}

	/**
	 * Any warnings related to the JQL query.
	 * @return warningMessages
	 **/
	public List<String> getWarningMessages() {
		return warningMessages;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class SearchResults {\n" +
			"    expand: " + toIndentedString(expand) + "\n" +
			"    issues: " + toIndentedString(issues) + "\n" +
			"    maxResults: " + toIndentedString(maxResults) + "\n" +
			"    names: " + toIndentedString(names) + "\n" +
			"    schema: " + toIndentedString(schema) + "\n" +
			"    startAt: " + toIndentedString(startAt) + "\n" +
			"    total: " + toIndentedString(total) + "\n" +
			"    warningMessages: " + toIndentedString(warningMessages) + "\n" +
			"}";
		return sb;
	}
}
