/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.HashMap;

/**
 * Issue security level member.
 **/

public class SecurityLevelMember extends HashMap<String, Object> {


	private SecurityLevelMemberHolder holder;

	/**
	 * The ID of the issue security level member.
	 **/

	private String id;

	/**
	 * The ID of the issue security level.
	 **/

	private String issueSecurityLevelId;

	/**
	 * The ID of the issue security scheme.
	 **/

	private String issueSecuritySchemeId;


	private Boolean managed;

	public SecurityLevelMember() {
	}


	public SecurityLevelMember(
		String id,
		String issueSecurityLevelId,
		String issueSecuritySchemeId
	) {
		this.id = id;
		this.issueSecurityLevelId = issueSecurityLevelId;
		this.issueSecuritySchemeId = issueSecuritySchemeId;
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get holder
	 * @return holder
	 **/
	public SecurityLevelMemberHolder getHolder() {
		return holder;
	}

	/**
	 * Set holder
	 **/
	public void setHolder(SecurityLevelMemberHolder holder) {
		this.holder = holder;
	}

	public SecurityLevelMember holder(SecurityLevelMemberHolder holder) {
		this.holder = holder;
		return this;
	}

	/**
	 * The ID of the issue security level member.
	 * @return id
	 **/
	public String getId() {
		return id;
	}

	/**
	 * The ID of the issue security level.
	 * @return issueSecurityLevelId
	 **/
	public String getIssueSecurityLevelId() {
		return issueSecurityLevelId;
	}

	/**
	 * The ID of the issue security scheme.
	 * @return issueSecuritySchemeId
	 **/
	public String getIssueSecuritySchemeId() {
		return issueSecuritySchemeId;
	}

	/**
	 * Get managed
	 * @return managed
	 **/
	public Boolean getManaged() {
		return managed;
	}

	/**
	 * Set managed
	 **/
	public void setManaged(Boolean managed) {
		this.managed = managed;
	}

	public SecurityLevelMember managed(Boolean managed) {
		this.managed = managed;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {
		String sb = "class SecurityLevelMember {\n" +
			"    " + toIndentedString(super.toString()) + "\n" +
			"    holder: " + toIndentedString(holder) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"    issueSecurityLevelId: " + toIndentedString(issueSecurityLevelId) + "\n" +
			"    issueSecuritySchemeId: " + toIndentedString(issueSecuritySchemeId) + "\n" +
			"    managed: " + toIndentedString(managed) + "\n" +
			"}";
		return sb;
	}
}
