/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Details about the Jira instance.
 **/

public class ServerInformation {

	/**
	 * The base URL of the Jira instance.
	 **/

	private String baseUrl;

	/**
	 * The timestamp when the Jira version was built.
	 **/

	private Date buildDate;

	/**
	 * The build number of the Jira version.
	 **/

	private Integer buildNumber;

	/**
	 * The type of server deployment. This is always returned as *Cloud*.
	 **/

	private String deploymentType;

	/**
	 * The display URL of the Jira instance.
	 **/

	private String displayUrl;

	/**
	 * The display URL of the Servicedesk Help Center.
	 **/

	private String displayUrlServicedeskHelpCenter;

	/**
	 * Jira instance health check results. Deprecated and no longer returned.
	 **/

	private List<HealthCheckResult> healthChecks = null;

	/**
	 * The unique identifier of the Jira version.
	 **/

	private String scmInfo;

	/**
	 * The time in Jira when this request was responded to.
	 **/

	private Date serverTime;


	private ServerInformationServerTimeZone serverTimeZone;

	/**
	 * The name of the Jira instance.
	 **/

	private String serverTitle;

	/**
	 * The version of Jira.
	 **/

	private String version;

	/**
	 * The major, minor, and revision version numbers of the Jira version.
	 **/

	private List<Integer> versionNumbers = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The base URL of the Jira instance.
	 * @return baseUrl
	 **/
	public String getBaseUrl() {
		return baseUrl;
	}

	/**
	 * Set baseUrl
	 **/
	public void setBaseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
	}

	public ServerInformation baseUrl(String baseUrl) {
		this.baseUrl = baseUrl;
		return this;
	}

	/**
	 * The timestamp when the Jira version was built.
	 * @return buildDate
	 **/
	public Date getBuildDate() {
		return buildDate;
	}

	/**
	 * Set buildDate
	 **/
	public void setBuildDate(Date buildDate) {
		this.buildDate = buildDate;
	}

	public ServerInformation buildDate(Date buildDate) {
		this.buildDate = buildDate;
		return this;
	}

	/**
	 * The build number of the Jira version.
	 * @return buildNumber
	 **/
	public Integer getBuildNumber() {
		return buildNumber;
	}

	/**
	 * Set buildNumber
	 **/
	public void setBuildNumber(Integer buildNumber) {
		this.buildNumber = buildNumber;
	}

	public ServerInformation buildNumber(Integer buildNumber) {
		this.buildNumber = buildNumber;
		return this;
	}

	/**
	 * The type of server deployment. This is always returned as *Cloud*.
	 * @return deploymentType
	 **/
	public String getDeploymentType() {
		return deploymentType;
	}

	/**
	 * Set deploymentType
	 **/
	public void setDeploymentType(String deploymentType) {
		this.deploymentType = deploymentType;
	}

	public ServerInformation deploymentType(String deploymentType) {
		this.deploymentType = deploymentType;
		return this;
	}

	/**
	 * The display URL of the Jira instance.
	 * @return displayUrl
	 **/
	public String getDisplayUrl() {
		return displayUrl;
	}

	/**
	 * Set displayUrl
	 **/
	public void setDisplayUrl(String displayUrl) {
		this.displayUrl = displayUrl;
	}

	public ServerInformation displayUrl(String displayUrl) {
		this.displayUrl = displayUrl;
		return this;
	}

	/**
	 * The display URL of the Servicedesk Help Center.
	 * @return displayUrlServicedeskHelpCenter
	 **/
	public String getDisplayUrlServicedeskHelpCenter() {
		return displayUrlServicedeskHelpCenter;
	}

	/**
	 * Set displayUrlServicedeskHelpCenter
	 **/
	public void setDisplayUrlServicedeskHelpCenter(String displayUrlServicedeskHelpCenter) {
		this.displayUrlServicedeskHelpCenter = displayUrlServicedeskHelpCenter;
	}

	public ServerInformation displayUrlServicedeskHelpCenter(String displayUrlServicedeskHelpCenter) {
		this.displayUrlServicedeskHelpCenter = displayUrlServicedeskHelpCenter;
		return this;
	}

	/**
	 * Jira instance health check results. Deprecated and no longer returned.
	 * @return healthChecks
	 **/
	public List<HealthCheckResult> getHealthChecks() {
		return healthChecks;
	}

	/**
	 * Set healthChecks
	 **/
	public void setHealthChecks(List<HealthCheckResult> healthChecks) {
		this.healthChecks = healthChecks;
	}

	public ServerInformation healthChecks(List<HealthCheckResult> healthChecks) {
		this.healthChecks = healthChecks;
		return this;
	}

	public ServerInformation addHealthChecksItem(HealthCheckResult healthChecksItem) {
		if (this.healthChecks == null) {
			this.healthChecks = new ArrayList<>();
		}
		this.healthChecks.add(healthChecksItem);
		return this;
	}

	/**
	 * The unique identifier of the Jira version.
	 * @return scmInfo
	 **/
	public String getScmInfo() {
		return scmInfo;
	}

	/**
	 * Set scmInfo
	 **/
	public void setScmInfo(String scmInfo) {
		this.scmInfo = scmInfo;
	}

	public ServerInformation scmInfo(String scmInfo) {
		this.scmInfo = scmInfo;
		return this;
	}

	/**
	 * The time in Jira when this request was responded to.
	 * @return serverTime
	 **/
	public Date getServerTime() {
		return serverTime;
	}

	/**
	 * Set serverTime
	 **/
	public void setServerTime(Date serverTime) {
		this.serverTime = serverTime;
	}

	public ServerInformation serverTime(Date serverTime) {
		this.serverTime = serverTime;
		return this;
	}

	/**
	 * Get serverTimeZone
	 * @return serverTimeZone
	 **/
	public ServerInformationServerTimeZone getServerTimeZone() {
		return serverTimeZone;
	}

	/**
	 * Set serverTimeZone
	 **/
	public void setServerTimeZone(ServerInformationServerTimeZone serverTimeZone) {
		this.serverTimeZone = serverTimeZone;
	}

	public ServerInformation serverTimeZone(ServerInformationServerTimeZone serverTimeZone) {
		this.serverTimeZone = serverTimeZone;
		return this;
	}

	/**
	 * The name of the Jira instance.
	 * @return serverTitle
	 **/
	public String getServerTitle() {
		return serverTitle;
	}

	/**
	 * Set serverTitle
	 **/
	public void setServerTitle(String serverTitle) {
		this.serverTitle = serverTitle;
	}

	public ServerInformation serverTitle(String serverTitle) {
		this.serverTitle = serverTitle;
		return this;
	}

	/**
	 * The version of Jira.
	 * @return version
	 **/
	public String getVersion() {
		return version;
	}

	/**
	 * Set version
	 **/
	public void setVersion(String version) {
		this.version = version;
	}

	public ServerInformation version(String version) {
		this.version = version;
		return this;
	}

	/**
	 * The major, minor, and revision version numbers of the Jira version.
	 * @return versionNumbers
	 **/
	public List<Integer> getVersionNumbers() {
		return versionNumbers;
	}

	/**
	 * Set versionNumbers
	 **/
	public void setVersionNumbers(List<Integer> versionNumbers) {
		this.versionNumbers = versionNumbers;
	}

	public ServerInformation versionNumbers(List<Integer> versionNumbers) {
		this.versionNumbers = versionNumbers;
		return this;
	}

	public ServerInformation addVersionNumbersItem(Integer versionNumbersItem) {
		if (this.versionNumbers == null) {
			this.versionNumbers = new ArrayList<>();
		}
		this.versionNumbers.add(versionNumbersItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class ServerInformation {\n" +
			"    baseUrl: " + toIndentedString(baseUrl) + "\n" +
			"    buildDate: " + toIndentedString(buildDate) + "\n" +
			"    buildNumber: " + toIndentedString(buildNumber) + "\n" +
			"    deploymentType: " + toIndentedString(deploymentType) + "\n" +
			"    displayUrl: " + toIndentedString(displayUrl) + "\n" +
			"    displayUrlServicedeskHelpCenter: " + toIndentedString(displayUrlServicedeskHelpCenter) + "\n" +
			"    healthChecks: " + toIndentedString(healthChecks) + "\n" +
			"    scmInfo: " + toIndentedString(scmInfo) + "\n" +
			"    serverTime: " + toIndentedString(serverTime) + "\n" +
			"    serverTimeZone: " + toIndentedString(serverTimeZone) + "\n" +
			"    serverTitle: " + toIndentedString(serverTitle) + "\n" +
			"    version: " + toIndentedString(version) + "\n" +
			"    versionNumbers: " + toIndentedString(versionNumbers) + "\n" +
			"}";
		return sb;
	}
}
