/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The details of the statuses in the associated workflows.
 **/

public class StatusMetadata {

	/**
	 * The category of the status.
	 **/

	private CategoryEnum category;
	/**
	 * The ID of the status.
	 **/

	private String id;
	/**
	 * The name of the status.
	 **/

	private String name;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The category of the status.
	 * @return category
	 **/
	public CategoryEnum getCategory() {
		return category;
	}

	/**
	 * Set category
	 **/
	public void setCategory(CategoryEnum category) {
		this.category = category;
	}

	public StatusMetadata category(CategoryEnum category) {
		this.category = category;
		return this;
	}

	/**
	 * The ID of the status.
	 * @return id
	 **/
	public String getId() {
		return id;
	}

	/**
	 * Set id
	 **/
	public void setId(String id) {
		this.id = id;
	}

	public StatusMetadata id(String id) {
		this.id = id;
		return this;
	}

	/**
	 * The name of the status.
	 * @return name
	 **/
	public String getName() {
		return name;
	}

	/**
	 * Set name
	 **/
	public void setName(String name) {
		this.name = name;
	}

	public StatusMetadata name(String name) {
		this.name = name;
		return this;
	}


	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class StatusMetadata {\n" +
			"    category: " + toIndentedString(category) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"    name: " + toIndentedString(name) + "\n" +
			"}";
		return sb;
	}

	public enum CategoryEnum {

		TODO("TODO"), IN_PROGRESS("IN_PROGRESS"), DONE("DONE");


		String value;

		CategoryEnum(String v) {
			value = v;
		}

		@JsonValue
		public String value() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}
	}
}
