/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.ArrayList;
import java.util.List;

/**
 * Details of changes to a priority scheme's priorities that require suggested priority mappings.
 **/

public class SuggestedMappingsForPrioritiesRequestBean {

	/**
	 * The ids of priorities being removed from the scheme.
	 **/

	private List<Long> add = null;

	/**
	 * The ids of priorities being removed from the scheme.
	 **/

	private List<Long> remove = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The ids of priorities being removed from the scheme.
	 * @return add
	 **/
	public List<Long> getAdd() {
		return add;
	}

	/**
	 * Set add
	 **/
	public void setAdd(List<Long> add) {
		this.add = add;
	}

	public SuggestedMappingsForPrioritiesRequestBean add(List<Long> add) {
		this.add = add;
		return this;
	}

	public SuggestedMappingsForPrioritiesRequestBean addAddItem(Long addItem) {
		if (this.add == null) {
			this.add = new ArrayList<>();
		}
		this.add.add(addItem);
		return this;
	}

	/**
	 * The ids of priorities being removed from the scheme.
	 * @return remove
	 **/
	public List<Long> getRemove() {
		return remove;
	}

	/**
	 * Set remove
	 **/
	public void setRemove(List<Long> remove) {
		this.remove = remove;
	}

	public SuggestedMappingsForPrioritiesRequestBean remove(List<Long> remove) {
		this.remove = remove;
		return this;
	}

	public SuggestedMappingsForPrioritiesRequestBean addRemoveItem(Long removeItem) {
		if (this.remove == null) {
			this.remove = new ArrayList<>();
		}
		this.remove.add(removeItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class SuggestedMappingsForPrioritiesRequestBean {\n" +
			"    add: " + toIndentedString(add) + "\n" +
			"    remove: " + toIndentedString(remove) + "\n" +
			"}";
		return sb;
	}
}
