/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import lombok.Data;

import java.net.URI;

@Data
public class UserBean {

	/**
	 * The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*.
	 *
	 * -- GETTER --
	 *  The account ID of the user, which uniquely identifies the user across all Atlassian products. For example, *5b10ac8d82e05b22cc7d4ef5*.
	 *
	 *
	 * -- SETTER --
	 *  Set accountId
	 @return accountId
	 */
	private String accountId;

	/**
	 * Whether the user is active.
	 *
	 * -- GETTER --
	 *  Whether the user is active.
	 *
	 *
	 * -- SETTER --
	 *  Set active
	 @return active
	 */
	private Boolean active;

	/**
	 * -- GETTER --
	 *  Get avatarUrls
	 *
	 *
	 * -- SETTER --
	 *  Set avatarUrls
	 @return avatarUrls
	 */
	private AvatarUrlsBean avatarUrls;

	/**
	 * The display name of the user. Depending on the user’s privacy setting, this may return an alternative value.
	 *
	 * -- GETTER --
	 *  The display name of the user. Depending on the user’s privacy setting, this may return an alternative value.
	 *
	 *
	 * -- SETTER --
	 *  Set displayName
	 @return displayName
	 */
	private String displayName;

	/**
	 * This property is deprecated in favor of `accountId` because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.   The key of the user.
	 *
	 * -- GETTER --
	 *  This property is deprecated in favor of &#x60;accountId&#x60; because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.   The key of the user.
	 *
	 *
	 * -- SETTER --
	 *  Set key
	 @return key
	 */
	private String key;

	/**
	 * This property is deprecated in favor of `accountId` because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.   The username of the user.
	 *
	 * -- GETTER --
	 *  This property is deprecated in favor of &#x60;accountId&#x60; because of privacy changes. See the [migration guide](https://developer.atlassian.com/cloud/jira/platform/deprecation-notice-user-privacy-api-migration-guide/) for details.   The username of the user.
	 *
	 *
	 * -- SETTER --
	 *  Set name
	 @return name
	 */
	private String name;

	/**
	 * The URL of the user.
	 *
	 * -- GETTER --
	 *  The URL of the user.
	 *
	 *
	 * -- SETTER --
	 *  Set self
	 @return self
	 */
	private URI self;

	public UserBean accountId(String accountId) {
		this.accountId = accountId;
		return this;
	}

	public UserBean active(Boolean active) {
		this.active = active;
		return this;
	}

	public UserBean avatarUrls(AvatarUrlsBean avatarUrls) {
		this.avatarUrls = avatarUrls;
		return this;
	}

	public UserBean displayName(String displayName) {
		this.displayName = displayName;
		return this;
	}

	public UserBean key(String key) {
		this.key = key;
		return this;
	}

	public UserBean name(String name) {
		this.name = name;
		return this;
	}

	public UserBean self(URI self) {
		this.self = self;
		return this;
	}
}
