/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Details of workflows and related statuses.
 **/

public class WorkflowReadResponse {

	/**
	 * List of statuses.
	 **/

	private Set<JiraWorkflowStatus> statuses = null;

	/**
	 * List of workflows.
	 **/

	private Set<JiraWorkflow> workflows = null;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * List of statuses.
	 * @return statuses
	 **/
	public Set<JiraWorkflowStatus> getStatuses() {
		return statuses;
	}

	/**
	 * Set statuses
	 **/
	public void setStatuses(Set<JiraWorkflowStatus> statuses) {
		this.statuses = statuses;
	}

	public WorkflowReadResponse statuses(Set<JiraWorkflowStatus> statuses) {
		this.statuses = statuses;
		return this;
	}

	public WorkflowReadResponse addStatusesItem(JiraWorkflowStatus statusesItem) {
		if (this.statuses == null) {
			this.statuses = new LinkedHashSet<>();
		}
		this.statuses.add(statusesItem);
		return this;
	}

	/**
	 * List of workflows.
	 * @return workflows
	 **/
	public Set<JiraWorkflow> getWorkflows() {
		return workflows;
	}

	/**
	 * Set workflows
	 **/
	public void setWorkflows(Set<JiraWorkflow> workflows) {
		this.workflows = workflows;
	}

	public WorkflowReadResponse workflows(Set<JiraWorkflow> workflows) {
		this.workflows = workflows;
		return this;
	}

	public WorkflowReadResponse addWorkflowsItem(JiraWorkflow workflowsItem) {
		if (this.workflows == null) {
			this.workflows = new LinkedHashSet<>();
		}
		this.workflows.add(workflowsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class WorkflowReadResponse {\n" +
			"    statuses: " + toIndentedString(statuses) + "\n" +
			"    workflows: " + toIndentedString(workflows) + "\n" +
			"}";
		return sb;
	}
}
