/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * The details about a workflow validation error.
 **/

public class WorkflowValidationError {

	/**
	 * An error code.
	 **/

	private String code;


	private WorkflowElementReference elementReference;
	/**
	 * The validation error level.
	 **/

	private LevelEnum level;
	/**
	 * An error message.
	 **/

	private String message;
	/**
	 * The type of element the error or warning references.
	 **/

	private TypeEnum type;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * An error code.
	 * @return code
	 **/
	public String getCode() {
		return code;
	}

	/**
	 * Set code
	 **/
	public void setCode(String code) {
		this.code = code;
	}

	public WorkflowValidationError code(String code) {
		this.code = code;
		return this;
	}

	/**
	 * Get elementReference
	 * @return elementReference
	 **/
	public WorkflowElementReference getElementReference() {
		return elementReference;
	}

	/**
	 * Set elementReference
	 **/
	public void setElementReference(WorkflowElementReference elementReference) {
		this.elementReference = elementReference;
	}

	public WorkflowValidationError elementReference(WorkflowElementReference elementReference) {
		this.elementReference = elementReference;
		return this;
	}

	/**
	 * The validation error level.
	 * @return level
	 **/
	public LevelEnum getLevel() {
		return level;
	}

	/**
	 * Set level
	 **/
	public void setLevel(LevelEnum level) {
		this.level = level;
	}

	public WorkflowValidationError level(LevelEnum level) {
		this.level = level;
		return this;
	}

	/**
	 * An error message.
	 * @return message
	 **/
	public String getMessage() {
		return message;
	}

	/**
	 * Set message
	 **/
	public void setMessage(String message) {
		this.message = message;
	}

	public WorkflowValidationError message(String message) {
		this.message = message;
		return this;
	}

	/**
	 * The type of element the error or warning references.
	 * @return type
	 **/
	public TypeEnum getType() {
		return type;
	}

	/**
	 * Set type
	 **/
	public void setType(TypeEnum type) {
		this.type = type;
	}

	public WorkflowValidationError type(TypeEnum type) {
		this.type = type;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class WorkflowValidationError {\n" +
			"    code: " + toIndentedString(code) + "\n" +
			"    elementReference: " + toIndentedString(elementReference) + "\n" +
			"    level: " + toIndentedString(level) + "\n" +
			"    message: " + toIndentedString(message) + "\n" +
			"    type: " + toIndentedString(type) + "\n" +
			"}";
		return sb;
	}


	public enum LevelEnum {

		WARNING("WARNING"), ERROR("ERROR");


		String value;

		LevelEnum(String v) {
			value = v;
		}

		@JsonValue
		public String value() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}
	}

	public enum TypeEnum {

		RULE("RULE"), STATUS("STATUS"), STATUS_LAYOUT("STATUS_LAYOUT"), STATUS_PROPERTY("STATUS_PROPERTY"), WORKFLOW("WORKFLOW"), TRANSITION("TRANSITION"), TRANSITION_PROPERTY("TRANSITION_PROPERTY"), SCOPE("SCOPE"), STATUS_MAPPING("STATUS_MAPPING"), TRIGGER("TRIGGER");


		String value;

		TypeEnum(String v) {
			value = v;
		}

		@JsonValue
		public String value() {
			return value;
		}

		@Override
		public String toString() {
			return String.valueOf(value);
		}
	}
}
