/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import lombok.AllArgsConstructor;
import lombok.NoArgsConstructor;

import java.util.HashMap;

/**
 * Details about the server Jira is running on.
 **/
@NoArgsConstructor
@AllArgsConstructor
public class WorkflowTransitionProperty extends HashMap<String, Object> {

	/**
	 * The ID of the transition property.
	 **/

	private String id;

	/**
	 * The key of the transition property. Also known as the name of the transition property.
	 **/

	private String key;

	/**
	 * The value of the transition property.
	 **/

	private String value;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * The ID of the transition property.
	 * @return id
	 **/
	public String getId() {
		return id;
	}

	/**
	 * The key of the transition property. Also known as the name of the transition property.
	 * @return key
	 **/
	public String getKey() {
		return key;
	}

	/**
	 * The value of the transition property.
	 * @return value
	 **/
	public String getValue() {
		return value;
	}

	/**
	 * Set value
	 **/
	public void setValue(String value) {
		this.value = value;
	}

	public WorkflowTransitionProperty value(String value) {
		this.value = value;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {
		String sb = "class WorkflowTransitionProperty {\n" +
			"    " + toIndentedString(super.toString()) + "\n" +
			"    id: " + toIndentedString(id) + "\n" +
			"    key: " + toIndentedString(key) + "\n" +
			"    value: " + toIndentedString(value) + "\n" +
			"}";
		return sb;
	}
}
