/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

/**
 * The workflows that use this status. Only available if the `workflowUsages` expand is requested.
 **/

public class WorkflowUsages {

	/**
	 * Workflow ID.
	 **/
	private String workflowId;

	/**
	 * Workflow name.
	 **/
	private String workflowName;

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Workflow ID.
	 * @return workflowId
	 **/
	public String getWorkflowId() {
		return workflowId;
	}

	/**
	 * Set workflowId
	 **/
	public void setWorkflowId(String workflowId) {
		this.workflowId = workflowId;
	}

	public WorkflowUsages workflowId(String workflowId) {
		this.workflowId = workflowId;
		return this;
	}

	/**
	 * Workflow name.
	 * @return workflowName
	 **/
	public String getWorkflowName() {
		return workflowName;
	}

	/**
	 * Set workflowName
	 **/
	public void setWorkflowName(String workflowName) {
		this.workflowName = workflowName;
	}

	public WorkflowUsages workflowName(String workflowName) {
		this.workflowName = workflowName;
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class WorkflowUsages {\n" +
			"    workflowId: " + toIndentedString(workflowId) + "\n" +
			"    workflowName: " + toIndentedString(workflowName) + "\n" +
			"}";
		return sb;
	}
}
