/**
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 * <p>
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-8b1a1ff5508af1eb786f141e37a6e5e53cbc3737
 * Contact: ecosystem@atlassian.com
 * <p>
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.atlassian.jira.v3.model;

import java.util.LinkedHashSet;
import java.util.Set;

/**
 * Details about a workflow configuration update request.
 **/

public class WorkflowTransitionRulesDetails {


	private WorkflowId workflowId;

	/**
	 * The list of connect workflow rule IDs.
	 **/

	private Set<String> workflowRuleIds = new LinkedHashSet<>();

	/**
	 * Convert the given object to string with each line indented by 4 spaces
	 * (except the first line).
	 */
	private static String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	/**
	 * Get workflowId
	 * @return workflowId
	 **/
	public WorkflowId getWorkflowId() {
		return workflowId;
	}

	/**
	 * Set workflowId
	 **/
	public void setWorkflowId(WorkflowId workflowId) {
		this.workflowId = workflowId;
	}

	public WorkflowTransitionRulesDetails workflowId(WorkflowId workflowId) {
		this.workflowId = workflowId;
		return this;
	}

	/**
	 * The list of connect workflow rule IDs.
	 * @return workflowRuleIds
	 **/
	public Set<String> getWorkflowRuleIds() {
		return workflowRuleIds;
	}

	/**
	 * Set workflowRuleIds
	 **/
	public void setWorkflowRuleIds(Set<String> workflowRuleIds) {
		this.workflowRuleIds = workflowRuleIds;
	}

	public WorkflowTransitionRulesDetails workflowRuleIds(Set<String> workflowRuleIds) {
		this.workflowRuleIds = workflowRuleIds;
		return this;
	}

	public WorkflowTransitionRulesDetails addWorkflowRuleIdsItem(String workflowRuleIdsItem) {
		if (this.workflowRuleIds == null) {
			this.workflowRuleIds = new LinkedHashSet<>();
		}
		this.workflowRuleIds.add(workflowRuleIdsItem);
		return this;
	}

	/**
	 * Create a string representation of this pojo.
	 **/
	@Override
	public String toString() {

		String sb = "class WorkflowTransitionRulesDetails {\n" +
			"    workflowId: " + toIndentedString(workflowId) + "\n" +
			"    workflowRuleIds: " + toIndentedString(workflowRuleIds) + "\n" +
			"}";
		return sb;
	}
}
